### ISSUE TITLE
Can only go Up in copy history

### ISSUE THREAD

**Issue by JSebastianN** [ffMathy/Shapeshifter#10]
On some computers(or keyboards?) I can only go up in the copy history.
For some reason, arrow down key, does nothing. I can cycle up and at the top, return to the bottom or I can use the mouse to select the wanted element.

**Comment by ffMathy** [comment]
Interesting. What OS does this happen on? Is it a laptop or a desktop? If it is a laptop, is an external keyboard being used?

**Comment by ffMathy** [comment]
I can't solve this issue if you can't provide the details I need.

**Comment by JSebastianN** [comment]
I'm sorry, I didn't read your first post.

On my workstation, which is a laptop with an external keyboard, it works
just fine on either keyboard.
My private desktop computer is the problem.

Both run Windows8 Pro.


--
Venlig hilsen/Best regards
Johannes Sebastian
js@johannessebastian.dk

2015-08-10 8:08 GMT+02:00 Mathias Lykkegaard Lorenzen <
notifications@github.com>:

**Comment by ffMathy** [comment]
Do you have any other hot key based programs running that might be using keyboard hooks? Any applications that react to key combinations like Shapeshifter does?

Note: It doesn't have to be the same combinations.

**Comment by JSebastianN** [comment]
I shall investigate :)

--
Venlig hilsen/Best regards
Johannes Sebastian
js@johannessebastian.dk

2015-08-10 14:16 GMT+02:00 Mathias Lykkegaard Lorenzen <
notifications@github.com>:

**Comment by KoalaBear84** [comment]
This tool can help:
http://www.nirsoft.net/utils/hot_keys_list.html

**Comment by ffMathy** [comment]
Nice @KoalaBear84 - let's hope it also displays general hotkeys that are not registered in Windows, such as the ones overriding default ones (like Shapeshifter does).

**Comment by JSebastianN** [comment]
It seems I only have one hotkey registered...



[image: Billede indsat i tekst 1]

--
Venlig hilsen/Best regards
Johannes Sebastian
js@johannessebastian.dk

2015-08-10 16:26 GMT+02:00 Mathias Lykkegaard Lorenzen <
notifications@github.com>:

**Comment by JSebastianN** [comment]
I'll be upgrading to Win10 not long from now and I can try out another
keyboard.
Let me do those things and get back.

If it doesn't help, I has to some rare driver or hardware issue related
specifically to my computer, since no one else is experiencing it...

--
Venlig hilsen/Best regards
Johannes Sebastian
js@johannessebastian.dk

2015-08-10 21:03 GMT+02:00 Johannes Sebastian <js@johannessebastian.dk>:

**Comment by JSebastianN** [comment]
With WIn10 and Shapeshifter version 5 beta, I can go up/down in the paste-list.(No hardware changes)
Version 4 download link is currently broken so I havn't tested that.

**Comment by ffMathy** [comment]
Version 4 download link should work. Can you try again?

Shapeshifter 5 does not yet hook into CTRL+V, which I think is the part that causes this bug.

I will therefore keep this issue open until we can confirm that this issue is resolved after integrating Shapeshifter to CTRL+V.

**Comment by JSebastianN** [comment]
Sure, aha.

But I dont seem to be able to reach the old installer, I've tried the Link from facebook http://flamefusion.net/software/shapeshifter
and the one on CNet.http://download.cnet.com/Shapeshifter/3000-2384_4-75338154.html

**Comment by ffMathy** [comment]
Very interesting! I see!

I thought this had been fixed. I'll work on that right now. Thanks for the report.

**Comment by ffMathy** [comment]
It should be back online again.

**Comment by JSebastianN** [comment]
Ok.
So it's the same in Windows10.
But, with another keyboard, it works!

So, my Logitech MK 250 is to blame.

--
Venlig hilsen/Best regards
Johannes Sebastian
js@johannessebastian.dk

2015-08-19 17:25 GMT+02:00 Mathias Lykkegaard Lorenzen <
notifications@github.com>:

**Comment by ffMathy** [comment]
That's very interesting! Not sure what I can do about this, but I wonder if other keyboards produce the same effect. I think I'll buy that keyboard and test it out one day.

**Comment by JSebastianN** [comment]
Don't, I somehow foresee I'll have a spare in the near future :)

PM me your address and I'll mail in when I manage to acquire a replacement.
js@johannessebastian.dk

--
Venlig hilsen/Best regards
Johannes Sebastian
js@johannessebastian.dk

2015-08-19 19:38 GMT+02:00 Mathias Lykkegaard Lorenzen <
notifications@github.com>:

**Comment by ffMathy** [comment]
This has now been resolved.
