### ISSUE TITLE
Key down interceptor doesn't work in some scenarios

### ISSUE THREAD

**Issue by ffMathy** [ffMathy/Shapeshifter#114]
Title speaks for itself. Only for some keyboards.

**Comment by ffMathy** [comment]
More information:

http://stackoverflow.com/questions/21129721/how-does-this-bitmask-apply-to-lparam-wm-hotkey

**Comment by KoalaBear84** [comment]
The title may speak for itself. But do we have ANY clue about what situations?

It is really a different keyboard? Are those mostly/only laptop keyboards? Do they have other special software/drivers installed? Is it when some special software is installed or active?

**Comment by ffMathy** [comment]
No idea - that's the scary part. It just doesn't work at my work. And for obvious reasons, I can't debug the problem there. I think I will try enabling logging to a disk in a future commit or something.

I have a theory that it might be caused because so many keys are down at once. The up key works fine though - it's just the down key. Could also be because modifier keys are held down, and the key code is mutated somehow based on that.

**Comment by ffMathy** [comment]
Could try throwing an exception if the return code is non-zero. I will work on that when I get home.

**Comment by ffMathy** [comment]
Hmmm, we apparently already do that.

I'll be checking out the NirSoft hotkey utility tomorrow, to see if the hotkey is somehow taken on that machine.

**Comment by ffMathy** [comment]
I can't continue with this until #122 is fixed. Help is needed.

**Comment by ffMathy** [comment]
NirSoft hotkey utility reports none of the needed hotkeys as taken. I find that very strange. I can't seem to find anyone else who has the same issues as well either.

I wonder if it has something to do with the language of the system installed. I have English.

**Comment by KoalaBear84** [comment]
I also think that it does not show ALL keyboard combinations that will be handled. But only the keyboard shortcuts that are registered with Windows. I also think that ShapeShifter won't be in the list, because it probably 'snifs' / intercepts keys(trokes). So it's not registered as "CTRL + V". Also it therefore will technically not be possible to show all that will be handled, because it's programmatically decided.

**Comment by ffMathy** [comment]
Shapeshifter does use Hotkeys now. It didn't last time you used the program. This also means that it is now impossible to disconnect the key hook (really nice).

I actually got permission from my employer to bring the keyboard home with me and try it out. I will post my findings shortly hopefully.

**Comment by ffMathy** [comment]
Oh my god. I suspect it's just low quality hardware. Apparently, some keyboards don't allow many keys pressed at once.

**Comment by KoalaBear84** [comment]
Aww no. And you are trying to code on that?? :D

Take this, you need it:
![image](https://cloud.githubusercontent.com/assets/5886900/12429746/40228ef4-beec-11e5-985b-f3d8c352668d.png)

And get yourself at work a new keyboard.
