### ISSUE TITLE
Add scroll wheel support

### ISSUE THREAD

**Issue by Eraknelo** [ffMathy/Shapeshifter#135]
For me personally, scroll wheel support is a must-have, like the earlier versions.
It just makes it so much faster to use.

A scroll up will simply emulate the arrow up event, and vice-versa for scroll down.

**Comment by ffMathy** [comment]
Hmmm, I will try to add this as a direct event listener on the window. If not, I think we need a mouse hook (which I would mostly avoid). Have you guys got any ideas on how to solve it more effectively and creatively?

**Comment by ffMathy** [comment]
Just tried a general mouse wheel event. It doesn't fire. Not even when holding the mouse over the window as it is shown.

**Comment by ffMathy** [comment]
Interesting.

https://msdn.microsoft.com/da-dk/library/system.windows.input.mouse.addpreviewmousewheelhandler(v=vs.110).aspx

When I use that function, I actually get wheel events (but only when the mouse is over the window). I wonder if we can use that somehow.

**Comment by ffMathy** [comment]
#137 is where this will be fixed. We still need to switch to a window message hook to get full support for things like horizontal scrolling (swapping between command panes).

Also still need to expand the window to be the full size of the screen.

**Comment by ffMathy** [comment]
This is now done - waiting for build results so that I can merge (it might be that there are still some tests missing).

**Comment by Eraknelo** [comment]
Beautiful. I can now use this application properly :D Great work man. Will try @ home.

**Comment by KoalaBear84** [comment]
I first tested it. Here it scrolls in the opposite of what I expect.

When I scroll up, I expect it to go up the in the list. From a programmer experience I can understand it is coded like this, because the items are ordered descending in time, newest on top. :)

@Eraknelo Can you check if it works OK for you?

**Comment by ffMathy** [comment]
I agree actually that the scrolling should be turned around. But I also believe that it should respect the Windows 10 setting which allows reversing it.

Good suggestion. I reopened the issue.

**Comment by ffMathy** [comment]
I have now fixed the scrolling direction.

**Comment by KoalaBear84** [comment]
Great.

I tried to find anything about the Windows 10 option, but didn't find anything.

It looks like this is vendor specific. Can you check at your side? I also guess when you have reversed it, every app will get the 'right -> reversed' delta's through and this should automatically work.

http://superuser.com/questions/948348/how-can-i-invert-touchpad-scroll-direction-on-windows-10
