### ISSUE TITLE
Challenge: Reduce complexity of GetPathSegmentsInCommonCount

### ISSUE THREAD

**Issue by ffMathy** [ffMathy/Shapeshifter#142]
Hey everyone interested (I'm looking at you @dvitonis, @Zargess, @Eraknelo and @KoalaBear84).

The code of Shapeshifter is starting to get pretty damn clean. Uncle Bob would have been proud. However, there is still one single function in the code that is bothering me. It's called `GetPathSegmentsInCommonCount` and is located in the `FileManager`.

The code (and its dependent functions) are shown below.

```csharp
static int GetPathSegmentsInCommonCount(IReadOnlyCollection<string> paths)
{
    var commonIndex = 0;
    foreach (var originPath in paths)
    {
        var originSegments = GetPathSegments(originPath);
        for (var index = 0; index < originSegments.Length; index++)
        {
            var originSegment = originSegments[index];
            foreach (var referencePath in paths)
            {
                var referenceSegments = GetPathSegments(referencePath);
                if (index >= referenceSegments.Length)
                {
                    return commonIndex;
                }

                var referenceSegment = referenceSegments[index];
                if (originSegment != referenceSegment)
                {
                    return commonIndex;
                }
            }
            commonIndex++;
        }
    }

    return commonIndex;
}

static string[] GetPathSegments(string originPath)
{
    return originPath.Split('\\', '/');
}
```

Normally I'm pretty good at making code clean and easy to read (by reducing the amount of lines per function, reducing nesting, and naming methods clearly after their intent), but *this monster is so hard to clean up*.

Any suggestions are welcome. I have given up on that method.

For those curious about what it's for, take a look at one of the tests for it:

```csharp
[TestMethod]
public void CanGetCommonPathWithBiggestPathInMiddle()
{
    var container = CreateContainer();
    var fileManager = container.Resolve<IFileManager>();

    var commonPath = fileManager.FindCommonFolderFromPaths(
        new[]
        {
            "foo\\bar",
            "foo\\bar\\baz\\lol",
            "foo\\bar\\baz"
        });

    Assert.AreEqual("foo\\bar", commonPath);
}
```

So `FindCommonFolderFromPaths` finds the shortest path that all of the paths provided have in common. It uses `GetPathSegmentsInCommonCount` for this, which fetches the amount of path segments (in this case `"foo"` and `"bar"`, with a count of `2`) that the paths have in common.

Let the challenge begin! I hope you'll add some proposals.

**Comment by KoalaBear84** [comment]
I don't know if this will help you:
http://stackoverflow.com/a/3450627/951001

Without the over optimizing two first ifs, which do not make it clearer and are absolutely not need :P

Besides that the second if just returns the first item, which can be very wrong either...

**Comment by dvitonis** [comment]
@KoalaBear84 links to nice article for optimization, but if you want just to strip the same into less lines, LINQ will help.

This is my take:
```
static int GetCommonSegmentCount(IReadOnlyCollection<string> paths)
        {
            var splitPaths = paths
                .Select(p => p.Split('\\', '/'))
                .ToList();
            var commonCount = splitPaths
                .Select(p => p.TakeWhile((s, i) => 
                    splitPaths.All(sp => sp.Count() > i && sp[i] == s)))
                .Max(p => p.Count());

            return commonCount;
        }
```

**Comment by ffMathy** [comment]
Nice. But less lines isn't always more readable. Despite that, your LINQ variant is even more readable than the one I made.

But it must be possible to make it more readable yet.

**Comment by dvitonis** [comment]
I absolutely agree. I wouldn't know what this function does just looking at the code.

**Comment by ffMathy** [comment]
Thanks for that! And cool that you added additional tests.
