### ISSUE TITLE
Make the length of time one needs to hold Ctrl-V configurable

### ISSUE THREAD

**Issue by ADHdev** [ffMathy/Shapeshifter#154]
For those of us who press keys longer than we should, a configurable hold timer would be useful. I'd give it a value like 250ms, maybe even 500ms or a full 1000ms if I find myself unable to manage a simple paste in that time.

Currently, since my fingers aren't very fast, I often see a white flash in the upper right corner of my monitor while I'm doing frequent pasting. It's distracting on my dark screen.

Thanks for considering this feature request. Shapeshifter is great software, and I look forward to the next version!

**Comment by ffMathy** [comment]
This is a great idea. I'll make that possible.

**Comment by dvitonis** [comment]
I have a similar problem - everytime I try to quickly paste something it doesn't seem to progress the ctrl+v keybinding and I end up writing just letter `v`.

**Comment by ffMathy** [comment]
Fixed. Will be released when #162 is merged to `master`.
