### ISSUE TITLE
Interaction with key managers

### ISSUE THREAD

**Issue by Zargess** [ffMathy/Shapeshifter#156]
I have a key manager called KeePass and it has the option to put a code into the clipboard for a limited amount of time and then delete it. However the old version of this program keeps the code on the list even after the time limit so it would be awesome if the new version could handle that other programs deletes elements on the list.

**Comment by ffMathy** [comment]
Hmmm interesting! For how long is the item retained in the clipboard?

**Comment by Zargess** [comment]
For KeePass it is 12 seconds but i don't know about other tools :)

**Comment by ffMathy** [comment]
#156 will fix this.
