### ISSUE TITLE
Paste as plain text in Word

### ISSUE THREAD

**Issue by msuguy71** [ffMathy/Shapeshifter#158]
After copying some items into the clipboard, I went to 'Paste as plain text' some text into a Word document.  When I released Ctrl-V, nothing showed up.  I held Ctrl-V again and found that it pasted into Shapeshifter again.  I am able to replicate this infinitely and have five instances of the same text in the clipboard and none in my document.  The 'Paste' option works though.

**Comment by Ardakilic** [comment]
Not related, but I use puretext to "paste as plain text".

http://stevemiller.net/puretext/

I even set "ctrl+shift+z" shortcut for this, so I can both use "ctrl+shift+v" and "ctrl+shift+z" together.

**Comment by ffMathy** [comment]
Thanks for reporting this. Will look into it.

**Comment by ffMathy** [comment]
This has now been resolved. It will be released when #162 is merged in to master.
