### ISSUE TITLE
Make the UpdateService work

### ISSUE THREAD

**Issue by ffMathy** [ffMathy/Shapeshifter#16]
Right now, the UpdateService does indeed download an update, but only launches it. It doesn't actually install it properly, and doesn't close the previous instance either.

**Comment by ffMathy** [comment]
Done, but can't test until next month.

**Comment by KoalaBear84** [comment]
Hi Mathias, How's your baby? :)

Unfortunately haven't had time last month. In the middle of moving houses.

How are you doing?

**Comment by ffMathy** [comment]
I have been busy with my job at eBay. It is so exciting that I sometimes do eBay related stuff outside working hours.

I will work on Shapeshifter again soon.
