### ISSUE TITLE
Use Aero color for design

### ISSUE THREAD

**Issue by ffMathy** [ffMathy/Shapeshifter#164]
Right now, blue is always used.

**Comment by ffMathy** [comment]
Hmm, this is more complicated than I first thought if we are to still have animations (with storyboards). The storyboards do not allow a `DynamicResource` reference, and so I am currently experimenting with replacing the storyboards programmatically.

It does not seem to work yet, so I will have to brainstorm this for a while.

**Comment by ffMathy** [comment]
I have asked this question which describes the issue in more detail: http://stackoverflow.com/questions/38390544/changing-color-used-in-storyboards

**Comment by ffMathy** [comment]
A suitable workaround could be this: http://stackoverflow.com/questions/8558781/coloranimation-workaround-for-dynamicresource

**Comment by KoalaBear84** [comment]
Funny that I visited that page this morning, to help to find a solution. But I have 'zero' knowledge of how it works. Hopefully you can figure it out with another workaround which you came up on the workaround page. (To make things complicated)

**Comment by ffMathy** [comment]
I figured out how to get it working through a minor hack that seems okay. Shapeshifter is starting to look very sexy! And it now has some nice little animations and effects that I added too.
