### ISSUE TITLE
Shapeshifter won't install

### ISSUE THREAD

**Issue by ffMathy** [ffMathy/Shapeshifter#170]
It just requests to run as administrator but never really starts up. If possible, we should make a test for this as well.

**Comment by kalzi** [comment]
Same issue identified - Win7 SP1 X64 | v6.1.1930

**Comment by ffMathy** [comment]
Hmmm. Can anyone find the version where this became a problem?

**Comment by ffMathy** [comment]
I have added a logging mechanism now, and it seems to reveal that the issue happens when code-signing the installed Shapeshifter assemblies. Will fix soon.

**Comment by hxsf** [comment]
same.

and the log file:
```
Information: Aero color was changed to #140C131A.
Information: Window message hook was constructed using 5 interceptors.
Information: Processing given command line arguments.
Information: Running no-argument argument processors since no single argument processor was used.
Information: Current process is elevated.
Information: Running installation procedure.
Information: Install directory prepared.
Information: Executable and manifest written to install directory.
```

**Comment by ffMathy** [comment]
The latest version now doesn't crash and installs to `C:\Program Files\Shapeshifter`, but doesn't launch the newly installed file. If you go there manually and launch `Shapeshifter.exe`, all should be fine.

**Comment by ffMathy** [comment]
This issue now appears to be solved, at least when running it on my own machine.

Thank you for taking the time to report this - much appreciated!
