### ISSUE TITLE
Crash at startup v 6.1.1943.0

### ISSUE THREAD

**Issue by msuguy71** [ffMathy/Shapeshifter#180]
When starting version 6.1.1943.0 program crashes immediately.  If run as administrator, crash does not occur, but shapeshifter's UI intermittently shows up.  For example, the first time it ran as admin, then crashed when left clicking on UI.  Next start up as admin does not bring up UI with ctrl-v

Crash on startup without admin:

![crash](https://cloud.githubusercontent.com/assets/7312961/17122935/dc00c0d4-52ad-11e6-886e-9222477e71d3.jpg)

Crash when clicking LMB on shapeshifter UI (the inner part where you select which clipboard item you want, not the UI with paste or paste as plain text):

![crashlmbonui](https://cloud.githubusercontent.com/assets/7312961/17123019/81fa9582-52ae-11e6-9cc0-5c839ac0fd61.png)

**Comment by ffMathy** [comment]
I currently have a lot of stuff to do and a lot of stuff going on in my life, but I will get back to Shapeshifter within the next 3 months I believe.

Feel free to also fix the issue by making a pull request - then I will just merge it in. It's open source - let's use that!

**Comment by ffMathy** [comment]
This should be resolved in the latest release that is coming up when #187 is merged.

If you would like to see more frequent releases, consider supporting us on Patreon: https://www.patreon.com/user?u=4197032
