### ISSUE TITLE
Version 5 inaccessible

### ISSUE THREAD

**Issue by nicchristeller** [ffMathy/Shapeshifter#182]
Version 6 is crashing on startup (same as issue #181), so I figured I'd run version 5 until that is sorted. 

The download link here is broken, and installers from elsewhere seem to try to download from the same place, so I can't even get v5.. Is it hosted anywhere else/is this a temporary problem?

**Comment by hxsf** [comment]
same

**Comment by ffMathy** [comment]
I have discontinued Shapeshifter 5. Hosting is not free, and I didn't receive enough donations to keep the sites running with all the traffic.

Shapeshifter 6 is currently broken too, but if you get an earlier release, it should work. However, Shapeshifter 6 is not production ready either (but please help us getting there by leaving us feedback).

I currently have a lot of stuff to do and a lot of stuff going on in my life, but I will get back to Shapeshifter within the next 3 months I believe.

Feel free to also fix the issue by making a pull request - then I will just merge it in. It's open source - let's use that!

**Comment by svenjochems** [comment]
Maybe it's possible to upload the version 5 Shapeshifter.application file so people can use this till version 6 becomes stable. I don't know if it's possible to add this in a release. Or you can add it as a zip file to this issue (I read GitHub allows zip files up to 25Mb).

**Comment by ffMathy** [comment]
That's a great idea. Except I don't have the files anymore. But if someone has them, I will upload them.

I have re-opened this ticket in case we find somebody who wants to help with that. Maybe you could try asking in the Facebook group?

**Comment by svenjochems** [comment]
I've got the application installed on a PC so maybe I'm able to extract the needed files from the appdata somewhere. But I think we still need an .application configuration file? I've got zero experience with clickonce applications so I don't know how the installation works. I'll try to add some files later if I can find any.

**Comment by ffMathy** [comment]
Interesting indeed. Keep me up to date with your findings.

**Comment by ffMathy** [comment]
Hmmm, I wonder if there are hosts out there who have re-hosted Shapeshifter also?

**Comment by ffMathy** [comment]
I just found an old backup of build 37, but it is quite old. Will host it soon. In the meanwhile, let's try to find build 107, which I believe was the latest version.

**Comment by hxsf** [comment]
@ffMat

**Comment by ffMathy** [comment]
Right click the executable, hit properties, and go to the details tab. It will say the assembly version and file version there.

**Comment by svenjochems** [comment]
I checked and the version I posted yesterday seems to be version 107. I tested it earlier and it can be executed directly from the executable and works perfectly. Only downside is that settings doesn't seem to be saved because every time I restart the 'first run' popup is shown.

**Comment by ffMathy** [comment]
I found it!

I have hosted it here: https://github.com/ffMathy/Shapeshifter/releases/tag/shapeshifter-v5.0.107

**Comment by Rotozaza** [comment]
You were 3 hours faster than I. 

I kept it, because I decided that I love ShapeShifter, although it crashes sometime Edges on 10 at the Ctrl-C moment from the address bar. 

So I did some eval and found one new player, close to your 5 design in simplicity, but it uses the cloud. 

I hope you'll find time. Thank a million.

**Comment by ffMathy** [comment]
Time will come back to me - Shapeshifter will always be one of my children 👍
