### ISSUE TITLE
Shapeshifter not be completely installed, the official website of the collapse, can repair it?

### ISSUE THREAD

**Issue by dnknn** [ffMathy/Shapeshifter#183]
Shapeshifter is very popular because it supports the clipboard Ctrl + V Press,
Because of this interaction is very convenient and very efficient and practical.
But now, very, very disappointed, very very sad ...
OF Can you answer the following three questions? ?
because:

First, Shapeshifter V6 versions do not install successfully.

Second, Shapeshifter V5 version can not be installed,
Because Shapeshifter V5 version of the official website server loses maintained.
The official website also not open
http://flamefusion.net

Third, we can continue to maintain Shapeshifter V5 version of the server network to download it? ? ? ?

Hope Shapeshifter author can answer these three fatal problem,
Because even now Shapeshifter installations are not installed, how to use it. . .....

![shapeshifter v5](https://cloud.githubusercontent.com/assets/10995302/18001215/3ce8a1cc-6bb4-11e6-8b33-e169908bbd05.png)
![shapeshifter v6](https://cloud.githubusercontent.com/assets/10995302/18001216/3eca718c-6bb4-11e6-9bf5-b8e8d44b45cb.png)
![flamefusion net](https://cloud.githubusercontent.com/assets/10995302/18001308/b8c4ca5a-6bb4-11e6-9b9c-0f2980bced1a.png)

**Comment by nicchristeller** [comment]
Identical to previous issue #182
