### ISSUE TITLE
"Select a Certificate" Messages

### ISSUE THREAD

**Issue by InsideLuke** [ffMathy/Shapeshifter#189]
Lately, I've been getting a lot of messages asking me to "Select a Certificate".  These Windows Security messages will pop up several times a day.

**Comment by ffMathy** [comment]
Are you running Shapeshifter 5 or Shapeshifter 6?

**Comment by InsideLuke** [comment]
Shapeshifter 5.0.0.107

**Comment by ffMathy** [comment]
I see. That version is discontinued and was only uploaded for legacy purposes. We don't have the source codes for it anymore, and we don't have the opportunity of fixing it.

Please refer to version 6 instead, which we are constantly improving!
