### ISSUE TITLE
Create a proper setup tool which can install Shapeshifter portably

### ISSUE THREAD

**Issue by ffMathy** [ffMathy/Shapeshifter#19]
For this task, we need the community's help.

In order to create the installer, we need to know what operating system you use. The more feedback we get on this, the easier it will be to make the setup tool.

**Comment by KoalaBear84** [comment]
I guess the support is Windows 7 or higher? I upgraded to Windows 10 already, but many users will 'never' do. Windows XP is already under 8%, and Vista is not even on the graph.

http://gs.statcounter.com/#os-ww-monthly-201407-201507

It's quite easy to create an installer with Inno Setup. But maybe you have other experiences with Microsoft Installer or WiX, or even another one.

Hmm. I see Visual Studio Installer Projects Extensions is not allowed to install on Community Edition, which is the wanted version to use. So it's only WiX which is the closest to Microsoft tooling.

http://stackoverflow.com/questions/30308580/tools-to-create-installers-or-setup-programs-in-visual-studio-2015

**Comment by ffMathy** [comment]
Let's continue the discussion in #17, since this is a duplicate of that.

To answer your question: Official support will only be for Windows 10. Windows 10 will be the last Windows release from Microsoft for a very, very, very long time. So Shapeshifter 6 is an investment into that.

However, that doesn't mean it won't work for Windows Vista and above (which I think it naturally will). Windows XP will be a problem though, but that's where the community comes in to fix the issues that may be there.

Minimum requirement is that the right version of the .NET framework is installed though.
