### ISSUE TITLE
Can't copy from Excel

### ISSUE THREAD

**Issue by nielsbosma** [ffMathy/Shapeshifter#195]

**Comment by d14m0nd0** [comment]
+1
I totally confirm this. When doing any copying within Excel while Shapeshifter is running, nothing gets copied not just into other programs, but inside Excel itself (e.g. from one cell to another). Copying in PowerPoint and Word works perfectly fine.

Guys, please please please fix this if/when time allows. I mean, I can live with a lot of things, but we're talking Excel here, which is a big deal when it comes to many if not most work occupations.

Details: Windows 10 x64, Office 2016 x86, shapeshifter-v6.1.1990

**Comment by KoalaBear84** [comment]
I see this is working now, at least in current release like "shapeshifter-v6.1.2090"

**Comment by ffMathy** [comment]
Thanks!
