### ISSUE TITLE
Can't paste screenshots taken with Lightshot

### ISSUE THREAD

**Issue by nielsbosma** [ffMathy/Shapeshifter#196]

**Comment by KoalaBear84** [comment]
Looks like this is the same as #200

Hopefully will be fixed soon, I see he is working on it. I have the same problem :)

**Comment by ffMathy** [comment]
Currently working on it. A bit more patience! I am very close in the `develop` branch.

**Comment by ffMathy** [comment]
Refer to #200 from now on, as Lightshot screenshots are now understood (visible in the list), but can't be pasted yet, which will be solved when that issue is solved.
