### ISSUE TITLE
Deleting Shapeshifter.log while running crashes the program dead (Win10, ss 6.1.1990)

### ISSUE THREAD

**Issue by d14m0nd0** [ffMathy/Shapeshifter#197]
Guys, a tiny thing here, but kinda of a major killjoy.

So, I have a script running every x minutes that clears the Temp folders on my PC so they don't get cluttered (Windows is still notoriously bad with this). I've just started using Shapeshifter (friggin l-o-v-e it btw!!!) and noticed it constantly crashing, I mean literally non-stop. After some poking around I found the reason.

Apparently, if you delete the c:\Users\USER-NAME-HERE\AppData\Local\Temp\Shapeshifter\Shapeshifter.log WHILE the software is running, the next time you try to copy anything - it kills Shapeshifter dead, I mean first and EM and them process dies. Here's the EM: https://i.imgur.com/iuYpagj.png

Hate to be Captain Obvious here, but would be nice to either lock the Shapeshifter.log while the program's running, or make it create a new one IF it can't find the old one.
As a temporary fix, I added the following at the end of my temp-cleaning script that simply creates an empty log file for SS to write in:
```
md c:\Users\USER-NAME-HERE\AppData\Local\Temp\Shapeshifter\
echo ' ' >c:\Users\USER-NAME-HERE\AppData\Local\Temp\Shapeshifter\Shapeshifter.txt
```

However, would be great to have proper fix for this though. But many thanks in advance in any case!

Details: Windows 10 x64 1607 14393.693, shapeshifter-v6.1.1990

**Comment by ffMathy** [comment]
I can no longer reproduce this on the latest release.

Here's what I tried:
- Start Shapeshifter. A log is then created.
- Delete the log while the software is running via Explorer.
- Copy something. The log file is re-created without a crash.
