### ISSUE TITLE
shapeshifter-v6.1.1990 cannot paste screenshott

### ISSUE THREAD

**Issue by jpokorny12** [ffMathy/Shapeshifter#198]
shapeshifter-v6.1.1990 cannot paste screenshott
shapeshifter-v5.0.107 - i see clipboard on [
![panel](https://cloud.githubusercontent.com/assets/26628909/24254289/cafd341e-0fe2-11e7-9d92-20f7f6b52541.PNG)
](url)

**Comment by ffMathy** [comment]
This is an issue for Shapeshifter 6.
