### ISSUE TITLE
Shapeshifter connecting to remote site when an error occurs?

### ISSUE THREAD

**Issue by gctommy** [ffMathy/Shapeshifter#199]
Malwarebytes will pop this up whenever Shapeshifter (5.0.0.107) has an error:

![survey](https://cloud.githubusercontent.com/assets/3850550/24284044/0790b240-10a4-11e7-8893-4879d7dff7d2.png)

Looks like it's trying to report the error to a malicious site? Anybody else seeing this?

**Comment by KoalaBear84** [comment]
I can't even go to that site here at work. I'm not running ShapeShifter.

**Comment by Trueinsanity** [comment]
this is coming from v5 of shapeshifter it is likely trying to relay crash info to  shapeshifter website which is no  longer owned by @ffMathy

**Comment by ffMathy** [comment]
Thanks @trueinsanity. You're right!
