### ISSUE TITLE
Ctrl button stick

### ISSUE THREAD

**Issue by jkdalton** [ffMathy/Shapeshifter#2]
I believe it is this program, but randomly, it seems to virtually hold the control button down. It is so random that it's difficult to repeat the issue.

**Comment by dvitonis** [comment]
I noticed the same. It actually gets impossible to work normally. I end up restarting OS.
I'm on Windows 8.1 , mostly using Visual studio, autohotkey.

**Comment by KoalaBear84** [comment]
Ahh. I guess this was the problem I had back then and why I stopped using it. I forgot that this was the problem, together with some exceptions.

**Comment by ffMathy** [comment]
It happens due to how Windows handles keyboard hooks. It's been a known bug in the Windows API for a while.

We'll see if Shapeshifter 5 can do something to get around it. I'll get back to this issue as we close in.

**Comment by ffMathy** [comment]
Can you figure out if it happens only for Visual Studio? If not, which applications does it happen in?

**Comment by ffMathy** [comment]
Note to self: Always let a KEYUP call for control go through, or else this might happen. Investigate if that is the cause.

**Comment by ffMathy** [comment]
This has now been resolved. Thanks for your contributions!
