### ISSUE TITLE
Clearing / Deleting history in Version 6

### ISSUE THREAD

**Issue by gctommy** [ffMathy/Shapeshifter#205]
How do you clear/delete the current history in the latest version 6?

In version 5 you would see a list in the taskbar and when needed, you would right-click and close them as if they were separate windows? In the latest version 6, since there is no taskbar elements, there is no way to clear the current history?

**Comment by ffMathy** [comment]
I never really thought the taskbar mode was actually being used.

Do you like the integrated mode better?

Hitting "Delete" on the keyboard should delete the active item.
