### ISSUE TITLE
Cant install on Windows 8.1

### ISSUE THREAD

**Issue by VojaM** [ffMathy/Shapeshifter#206]
I've downloaded the newest version and when I double click on exe file nothing happens.I can see in task manager that process has started but it wont install.What can I do?

Thanks!

**Comment by rubenspischedda** [comment]
The same happens to me on Windows 10.

**Comment by VojaM** [comment]
After a lot of attempts I finally managed to install it.I had to open properties of exe file and set to be run with administrator rights and set compatibility mode to Windows 8.
But definitely the installer is not very good and Mathy has to work on it a little bit more. :)
You can try to do what I did to see if it helps.I hope you will mange to install it.

**Comment by rubenspischedda** [comment]
No, it doesn't work. I tried also with compatibility mode set to Windows 7, and it doesn't work either.

**Comment by amips54** [comment]
I cannot get it to run on the last 6 W10 PC's I've built either.  Tried ALL modes & rights too. Gonna have to pull the Patreon support and go back to using DITTO unfortunately.

**Comment by rubenspischedda** [comment]
I think the problem is just the installer. Running the code from Visual Studio works fine, and it should be possible to copy the debug folder of the Visual Studio project and execute the .exe from there.

**Comment by ffMathy** [comment]
Hmmm, I will investigate installer issues soon. I am currently focused on a Shapeshifter website.

**Comment by ffMathy** [comment]
This has now been resolved.
