### ISSUE TITLE
Install bombs out: FileNotFoundException - Shapeshifter.WindowsDesktop.KeyboardHookInterception.dll 

### ISSUE THREAD

**Issue by oryz** [ffMathy/Shapeshifter#208]
Trying to install from latest .exe file it bombs with attached error:

![2017-08-01_1640](https://user-images.githubusercontent.com/20960028/28812704-46fda154-76d9-11e7-808b-ec20e87ef4ae.png)

Machine details: Windows 7 64 bit

**Comment by ffMathy** [comment]
This will be fixed soon.

**Comment by ffMathy** [comment]
This should be resolved now.
