### ISSUE TITLE
Windows 10: slow performance, causing control key to get stuck occasionally

### ISSUE THREAD

**Issue by gctommy** [ffMathy/Shapeshifter#210]
On Windows 10 I am running into the same issue as this person:

[https://www.reddit.com/r/Windows10/comments/3yj8bp/windows_key_is_stuck_but_not_physically/](https://www.reddit.com/r/Windows10/comments/3yj8bp/windows_key_is_stuck_but_not_physically/)

Turned off all my Accessibility settings for the keyboard and it didn't work.

Reinstalled my keyboard driver and it didn't work.

Went through all my tray icon programs one by one and by the time I turned off Shapeshifter, there were no more issues and my control key did not get stuck anymore.

With Shapseshifter off, my CTRL key seems faster / snappier. When it on, occasionally it would freeze up and I end up pasting something 2 or 3 times as it doesn't paste something right away or the control key gets stuck and I end up pasting just a "v" on CTRL+V key presses.

Anyone else on Windows 10 with this similar issue?

**Comment by kyle-charlton** [comment]
I don't know if this is exactly the same issue, but my CTRL key becomes virtually stuck when I press the V key when writing in some programs such as my browser or chat programs like messenger, I was not sure if it was Shapeshifter or not, so I did not submit it as a bug.
Its hard to test since its intermittent and will not trigger when I want it to for testing.
I am running windows 10

**Comment by gctommy** [comment]
> CTRL key becomes virtually stuck

Yes, it was intermittent for me as well. You should go through all your tray icon / background running programs like I did one by one to narrow down the source. For me, it was definitely Shapeshifter.

**Comment by santiagazo** [comment]
It has been the same for me. My CTRL key becomes intermittently stuck and causes problems as I try to work until I realize the problem (usually only seconds later). Rapidly hitting CTRL seems to release the "fake stick" but its a huge bother.

**Comment by mpratt14** [comment]
Are you all using the most recent v6 or the most recent v5?

I had issues with v6 but not this specific issue

I have had no issues with the most recent version 5 on Windows 10. However, pasting is indeed a little slower. I don't think this latency is avoidable though.

**Comment by santiagazo** [comment]
Just downloaded v6 tonight. I was probably using an older build previously. If I continue to experience the issue with v6 and win10 I'll update the thread.

**Comment by gctommy** [comment]
> Are you all using the most recent v6 or the most recent v5?

I was using the latest v6. Just downgraded back to v5.0.107, seems to be working ok for now.

**Comment by ffMathy** [comment]
This is interesting. Could you provide steps to reproduce?

**Comment by svenjochems** [comment]
I'm using latest v5 on win10 and have problems with CTRL key as well

**Comment by ffMathy** [comment]
Is it possible to create steps to reproduce the issue? Can we find a common scenario where it always happens?

**Comment by santiagazo** [comment]
I have not been able to figure out the trigger, but for me it's the alt and
ctrl key that get's virtually stuck and pressing the alt key repeatedly
unsticks both of them. I cannot at this point deduce that shapeshifter is
the issue as in talking with other programmers and windows buffs they've
also found that windows has the issue of keys getting stuck virtually from
time to time and that its a native bug they haven't been able to or haven't
chosen to fix for nearly a decade.

**Comment by svenjochems** [comment]
Had the issue again a few times today, but I was never able to reproduce it right after.
The problem always seems to be triggered when the "v" button is pressed.
I tried disabling flamefusion cache in settings (v5), no change.
Tomorrow I will work without shapeshifter to make sure nothing else is causing this problem.

**Comment by svenjochems** [comment]
I've had no issues in 2 days **without** shapeshifter.

**Comment by ffMathy** [comment]
And what about V6? The keyboard functionality has changed a lot between versions. Version 5 is not relevant anymore.

**Comment by svenjochems** [comment]
If I remember correctly I had some trouble installing V6. I'll try again or will wait for new release.

**Comment by ffMathy** [comment]
Yeah installation issues are being resolved as we speak.

**Comment by ffMathy** [comment]
Try the latest release. Installation issues should be resolved.
