### ISSUE TITLE
Copy history list appears off screen when using multiple monitors

### ISSUE THREAD

**Issue by kyle-charlton** [ffMathy/Shapeshifter#211]
I am having problems with the copy history list not appearing correctly after you press and hold the CTRL+V key on windows 10.

It appears to be a problem with the way I have my screens set up, I have 3 monitors, 2 are side by  side and the third is on the bottom (see diagram below)

![image](https://user-images.githubusercontent.com/12102133/32199923-24612bc6-bd8c-11e7-8d36-7e4ae193c276.png)

The copy history list does not appear anywhere, I can still use my keyboard to access the copy history but I can't see what I am selecting.

Sort of related to this issue is that my laptop has a 4k monitor and when I use just the laptop alone without the additional monitors the copy history list appears slightly off screen.

![image](https://user-images.githubusercontent.com/12102133/32200030-c733ef46-bd8c-11e7-8a80-05e52bb7dd2e.png)

**Comment by ffMathy** [comment]
This seems to be for Shapeshifter 5 and does not apply to Shapeshifter 6.
