### ISSUE TITLE
Shapeshifter needs an icon

### ISSUE THREAD

**Issue by ffMathy** [ffMathy/Shapeshifter#22]
We want Shapeshifter to have an icon, and we don't like the old Shapeshifter icon. Does anyone have any ideas in the community of what to use as icon? Are anyone up for the challenge of designing one?

We would like to have one that's simple and modern.

**Comment by KoalaBear84** [comment]
The old icons are more 'art' like icons, not related to a clipboard in any way, which does not have to be bad.

I've tried to create something the last 1,5 hours, but can't succeed. I'm not really a art guy :). Mostly succeed, it's hard to have a good icon at 16px, which is a very important size as it is probably the most seen one (tray icon).

I also like a 'flat' / modern / material like icon. Preferably with some sort of clipboard like icon. And maybe 'shapes', a lightning, or a 'manager' added to it. But to get all that to also look nice in 16px is maybe to much to get right. Hopefully someone with better art / design skills can help.

**Comment by ffMathy** [comment]
Thanks for your efforts! Wow, that's crazy. I think I might just buy an icon somewhere, or try desperately to design my own. Unless somebody else wants to give it a go as well?

**Comment by ffMathy** [comment]
I am bumping this up because of importance.

**Comment by ffMathy** [comment]
I am considering this icon at the moment:

https://www.iconfinder.com/icons/270476/abstract_power_shape_target_icon#size=512

**Comment by Eraknelo** [comment]
Needs more fire.

**Comment by ffMathy** [comment]
Loool :100:

**Comment by Eraknelo** [comment]
I honestly don't know. That icon isn't very distinctive though.

**Comment by dvitonis** [comment]
From the same place, this looks nice. Plus it looks like an `S`
https://www.iconfinder.com/icons/270487/abstract_digital_pixels_square_technology_icon#size=64

**Comment by ffMathy** [comment]
Nice! Thank you! We'll take it. I will buy it tomorrow, integrate it, and push it. This will make it possible for us to finally get a tray icon and get the rest of the tasks ans issues done!

Much appreciated.

**Comment by ffMathy** [comment]
I uploaded the SVG form here: https://onedrive.live.com/redir?resid=BF817E8DCD9F055B!805644&authkey=!AAYROLWW1S76gUw&ithint=file%2csvg

@dvitonis can you maybe continue the task from here? The purpose of this task is to just make the executable have the given icon.

You will need to create a separate branch for it (the master branch is protected), and then make a pull request.

**Comment by dvitonis** [comment]
That SVG is not exactly square. Do you have an ICO of it?

**Comment by ffMathy** [comment]
None was given to me. But you can use Axialis Iconoworkshop or whatever it is called. It is the best for creating icons.

**Comment by ffMathy** [comment]
I made an `.ICO` for you.

https://onedrive.live.com/redir?resid=BF817E8DCD9F055B!805649&authkey=!AMzPTRoGD-CDnwA&ithint=file%2cico
