### ISSUE TITLE
Overlay positioning (right vs left)

### ISSUE THREAD

**Issue by thegabriestein** [ffMathy/Shapeshifter#224]
Currently the overlay appears on the upper left corner of the screen with the action menu displaying outwards to the right side of the screen. Because a large percentage of the users (and at the present almost all of them), read from left to right, most of the content and interface you might be trying to interact with is blocked by the overlay. 

So mirroring the interface to the other side of the screen (like in v5) would allow for better use of screen space (especially when the left side of the screen is often empty). 

Potentially offer this as a setting in the menu, or allow the overlay to be manually positioned and have it remember it's location when opening each time. Maybe both? But multiple screens (and removing and adding displays like in presentations) could get kind of funky, so it's understandable if it only shows on active windows in the selected corners.

I do feel like higher on the screen is better typically as you want to match and contrast between what the clipboard list preview shows, and the context you're placing the item into. But selecting the corner could be the best option as well. So "Upper left, lower left, upper right, lower right." This would solve all the horizontal and vertical layout problems.

**Comment by thegabriestein** [comment]
Correct, because of the logic I mentioned (and being used to v5 on the right and it feeling correct), it should probably default to the right.

**Comment by ffMathy** [comment]
Position has been swapped.

**Comment by thegabriestein** [comment]
Yeah, good call. I think for the majority of users (especially early adopters), they'll benefit from the right oriented layout because it's much less utilized screen real estate. And down the road if it's a concern it can be added as a setting. 

Regarding how it's flipped. I was thinking that it would mirror all the commands and layout. So instead of Left Arrow closing the overlay, now it's Right Arrow (like it slides back into the right side of the screen, maybe should add this animation actually in the future?), and the action menu is triggered through Left Arrow because that's the direction it travels out now. 

Maybe sticky positioning as well which would let users flip the orientation, and also position it optimally. But active window tracking is arguably much more important for now. 

Also to consider: a need for a left handed layout because of Right To Left language would mean a need for translations and stability in a different language which would probably be much harder than simply another language because it would be a Right To Left language as well). Not impossible, just potentially a somewhat decent undertaking vs a simple mirroring of the interface.

**Comment by ffMathy** [comment]
Great minds think alike. This fix already includes a horizontal mirroring of it all, including hot keys.

As for right to left, let's handle that when it is requested.
