### ISSUE TITLE
Control + V doesn't always trigger the overlay on 6.1.2101

### ISSUE THREAD

**Issue by thegabriestein** [ffMathy/Shapeshifter#225]
It's been happening for the last couple releases. Seems like every 4-8 times holding Control + V the interface won't consistently show up, and the keys have to be released before pressing again to reset them and trigger the overlay. Fairly big influence on the subtle trust of the software and user experience. Reproduced on multiple Windows 10 machines.

Seems to be producible based on the frequency between triggering the overlay. If you open it fairly quickly through multiple fast Control+V commands, it will fail to open after a couple. Something to do with caching or writing to logs maybe?

**Comment by ffMathy** [comment]
I also believe this is highly related: #167 

I believe they are the same cause.

When Shapeshifter fails with this scenario, is it in reality because the CTRL key or something similar is blocked at a "keydown" state? Think about it.

**Comment by thegabriestein** [comment]
Looks like this occurs with either key combo, so:
1. Control down
2. V down
3. V up
4. Control up

Or, what I organically find myself doing after testing myself:
1. Control down
2. V down
3. Control up
4. V up

And yes I wouldn't be surprised if they're related issues and that the program doesn't release the control key until the paste completes or something (depends on command structures etc)

**Comment by KoalaBear84** [comment]
I always use the above scenario and was having the same problem. Maybe built in default logging for keypresses and functions in the software to maybe see what is causing it. I've tried to test this in v5 a lot.

Will start using / testing it when image functionality is restored.

**Comment by thegabriestein** [comment]
Also seems that whatever is causing the overlay to not appear consistently, also causes pasting to be very inconsistent even if you quickly press the keybind without waiting for the overlay to appear (a simple paste operation vs advanced operation through the overlay). I have my overlay delay set to 100ms by the way. Since I want the simple keybind to function immediately, and the overlay to appear quickly if I need it to. 

If you compare pasting behavior and speed of default W10 clipboard, still a decent gap between Shapeshifter's consistency and speed. Top priority bug in my opinion.

**Comment by thegabriestein** [comment]
Yeah at least a button in Settings to open the log folder, or a button to submit anonymous logs would be good as most users won't know how to do that. Should I add a wiki page about how to submit logs?

**Comment by ffMathy** [comment]
For now, you can find them in %TEMP%\Shapeshifter though. Just attach them here on GitHub.

**Comment by ffMathy** [comment]
I think this may have been resolved now!
