### ISSUE TITLE
Automatically submit all errors occured as GitHub issues

### ISSUE THREAD

**Issue by ffMathy** [ffMathy/Shapeshifter#226]
We could have an API key that only has access to create issues, which could then be responsible (via the website) for creating the issues.

Duplicates are instead upvoted.

Could be very useful.

**Comment by thegabriestein** [comment]
Yes, could be very useful, would probably need to limit it heavily somehow so it doesn't spam a couple hundred issues, potentially with an "automated bug notice" label? 

But upvoting the same error codes as duplicates would probably help a lot, so you have an idea of severity of a bug. 

Probably better handled with NewRelic or other monitoring platform though, and then roll ApDex drops into GitHub issues.

**Comment by ffMathy** [comment]
I really believe in having one central tool as much as possible though, at least until Shapeshifter becomes a source of income that we can truly dedicate our time to perfecting.

**Comment by ffMathy** [comment]
Done! Can't wait to see this in action!

**Comment by KoalaBear84** [comment]
Haha, me too, I will try it the next release, as I have a crash at startup.

**Comment by ffMathy** [comment]
It's live in a few minutes!

**Comment by ffMathy** [comment]
It is live!

**Comment by KoalaBear84** [comment]
Yes, runned it, crashed, KeyNotFoundException, but not reported?

**Comment by ffMathy** [comment]
@KoalaBear84 try shapeshifter-v6.2018.429.2437.

**Comment by ffMathy** [comment]
Hmmm @KoalaBear84 I just noticed your username was included in one of the log entries and that you edited it. I think this should be automatic. It should trim that from paths automatically. Sorry for the inconvenience.

**Comment by KoalaBear84** [comment]
Haha, nothing wrong with your eyes. Yes, I thought about that, if I needed to create a new ticket, but I think it is better to include it in this ticket indeed.

**Comment by thegabriestein** [comment]
Yeah I just wrote a comment about that in #344 about sanitizing logs a bit more, I'd definitely like to keep my username out of it etc.

**Comment by ffMathy** [comment]
Logs now fully anonymized.
