### ISSUE TITLE
Create Shapeshifter website

### ISSUE THREAD

**Issue by ffMathy** [ffMathy/Shapeshifter#227]
Could easily be hosted using GitHub pages, and then use the API on Azure.

Could use the same kind of design as https://fluent.microsoft.com with the parallax scrolling effect to demonstrate how Shapeshifter works.

Could also have a Patreon hall of fame in the top, as well as top GitHub contributors.

**Comment by ffMathy** [comment]
Closing this as it is actually done. Domain still pending. Should also probably add Patreon supporters and top GitHub contributors to the website too, but I will make separate issues for that.

**Comment by ffMathy** [comment]
Website can be seen here: https://ffmathy.github.io/Shapeshifter/

**Comment by KoalaBear84** [comment]
Looks great and simple! Now it also needs an updated screenshot too, where it is positioned on the right :P

**Comment by ffMathy** [comment]
Feel free to contribute! The website is inside the `docs` folder - all open source!
