### ISSUE TITLE
Re-visit Shapeshifter 5 source codes

### ISSUE THREAD

**Issue by ffMathy** [ffMathy/Shapeshifter#229]
I should take a look at Shapeshifter 5 source codes to see how it handles some of the issues Shapeshifter 6 is facing, and then re-use some of that code in a rewritten format until we find better solutions to the most common problems (image copying etc).

**Comment by thegabriestein** [comment]
Yeah, obviously there will be major differences in executing solutions, but it may be very instrumental to see how all the many use cases were solved. Definitely worth some time if it's indeed efficient.

**Comment by ffMathy** [comment]
I think it might be efficient.

**Comment by ffMathy** [comment]
This is no longer going to be needed, as I found a way to correctly represent images in a clean way now, which was the main motivation behind this before.
