### ISSUE TITLE
Detailed change logs included in updates

### ISSUE THREAD

**Issue by thegabriestein** [ffMathy/Shapeshifter#230]
A user may desire to reject an update or at least skip a version because of undesirable changes to the program. So at least offering detailed change logs helps them understand what's changed especially to see what might be causing bugs.

Excellent example is:
https://getsharex.com/changelog/

![](http://i.imgur.com/rjRenAK.png)

**Comment by ffMathy** [comment]
Changelogs on each release are now being auto-generated from closed periods. Every release will now contain detailed release notes.

@thegabriestein did you have in mind also showing that in a UI somehow?

The thing is, I don't like tools that pop up with an ugly dialog interrupting the user. If that's what we want, me must make it non-intrusive somehow.

Will close for now. If you had some UI stuff in mind too, we can open a new issue for that.

**Comment by thegabriestein** [comment]
Awesome! Great solution, just means the change notes will need to be relatively solid and thorough to also count as change logs. But if they are, that's a pretty efficient solution.

Well just a notification saying "Shapeshifter has been updated to x.x.xx" etc is good, and then ideally opening that notification would open to the change logs from the recent update so you could read them if desired (otherwise just close the notification). 

Maybe offer a setting to "Ask me to update instead of automatic updates", and then could use the interface above from ShareX which would have the changelog link (why they should update). 

But I'd definitely call this issue good for now!

**Comment by ffMathy** [comment]
Well it will link to the individual issues in the release, and also categorize them under bug fixes or new features.

Aa for the asking part, I actually don't want to give the community a choice of whether or not to update. It could potentially be a maintenance hell. It's very nice as a developer to be able to rely on everyone running the same version if they report bugs.
