### ISSUE TITLE
Notify users when Shapeshifter is updated

### ISSUE THREAD

**Issue by thegabriestein** [ffMathy/Shapeshifter#231]
Should have at least a simple popup or Windows notification alerting users the program has updated.

Potentially ask the user if they want to update, and offer link to change logs (#230)?

Show the build number, and offer user triggered updates through the settings interface?
![687474703a2f2f692e696d6775722e636f6d2f377148365831662e706e67](https://user-images.githubusercontent.com/10291839/39088032-1850f076-4560-11e8-99e3-a64187e7719d.png)

**Comment by ffMathy** [comment]
All done :+1:
