### ISSUE TITLE
Paste duration should have a number field as well

### ISSUE THREAD

**Issue by thegabriestein** [ffMathy/Shapeshifter#243]
In the settings menu, the current duration before overlay appears slider is probably unnecessary in terms of it's current value end points, since I doubt people will want to wait 3000 ms before it shows up. But maybe just allow people to put in a value instead of the slider? 

Don't know if that's easier or harder though. Seems like it's simpler and would allow people to customize more?

I know personally I want basically instantaneous simple pasting of the most recent item, and fairly snappy overlay triggering if I need to find a recent clipping. So I had it set at 100ms, but it seems like it's more stable and reliable at 200 ms. 

So at least changing the end values slightly might be good, or making it a value field. Thoughts?

**Comment by ffMathy** [comment]
I think both would be a good idea.

**Comment by ffMathy** [comment]
Done.
