### ISSUE TITLE
Maximum number of items in clipboard could cause lost data?

### ISSUE THREAD

**Issue by thegabriestein** [ffMathy/Shapeshifter#244]
As the program becomes more and more stable, it becomes easier and easier to trust it to hold important information temporarily. 

This introduces two factors:
1. Copying more than the user-selected amount of items in the deck and losing items off the bottom. So should it warn the user when they're approaching eg 20/25 copied items? Or maybe just allow 26/25 items and warn the user that they're over the set limit and to remove some items? Are there performance concerns with letting people copy a couple hundred things? 

I know from my experience, I like to keep it open for a whole work day and have a lot of stuff floating around and it's rare that I won't benefit from going back to an item from previous task earlier in the day and save a lot of time trying to find a certain email address etc that I copied earlier. I don't have an exact figure, but I'd be surprised if it's not over 100 items by the end of the day.

2. Shutting down the machine and losing data in the clipboard. Should there be a shut-down-hold warning saying "Review your clipboard before shutting down", or should it just auto save for the next session? How much risk if it doesn't auto-save? 

Also from experience, there have been times where the power has went out, or my computer has crashed or frozen, and I've lost information that was in the clipboard. Even though it's usually minor overall (eg a color hex code that I had to reference again). It would have saved some time if the session was saved unless cleared.

**Comment by ffMathy** [comment]
Is there currently a limit? I actually don't think so.

If there is, we should remove it. There should not be a limitation. We could however internally have a memory limitation, and then offload some of the older items to the disk, but I say we take that when the issue actually arises.

**Comment by thegabriestein** [comment]
Yes, here's the limit on items available for copying (testing it with 3 item max functions as I described):

![](https://i.imgur.com/GQCQ68g.png)

And it clears the items off the bottom when you copy any more than this amount. So the two items I mentioned above are still valid, primarily number 1.

**Comment by ffMathy** [comment]
So what you are proposing here is to increase the limit, right?

**Comment by ffMathy** [comment]
Fixed by removing the limit. I might have to find a way to restrict the amount of UI elements graphically though (to avoid the list becoming too long), but that is for another issue.
