### ISSUE TITLE
Shapeshifter won't start if already installed and original exe is opened

### ISSUE THREAD

**Issue by ffMathy** [ffMathy/Shapeshifter#248]
Today, when Shapeshifter first launches (when the user opens `shapeshifter.exe`), it copies itself into `C:\Program Files\Shapeshifter`. However, if the user doesn't open it from `C:\Program Files\Shapeshifter` and instead opens the original `shapeshifter.exe` from the downloads folder, it just closes.

Steps to reproduce:
1. Download Shapeshifter without having it installed already (clear the `C:\Program Files\Shapeshifter` folder).
2. Open Shapeshifter via the `Shapeshifter.exe` and accept the UAC dialog if it pops up.
3. Shapeshifter is now installed in `C:\Program Files\Shapeshifter` and is loaded from there silently.
4. Close Shapeshifter.
5. Try opening Shapeshifter again from the original `Shapeshifter.exe` file you downloaded. It won't open, but if you open via the one in `C:\Program Files\Shapeshifter`, it opens just fine.

**Comment by ffMathy** [comment]
Yeah that's pretty critical. Easy to solve. @gabriestein can you prioritize it in?

**Comment by thegabriestein** [comment]
@ffMathy Yeah I experienced this bug as well, definitely critical. I adjusted priority for it.

**Comment by ffMathy** [comment]
Fixed.

**Comment by ffMathy** [comment]
This has been fixed again, and tests have been made to prevent the issue in the future.
