### ISSUE TITLE
Latest release 'virus'

### ISSUE THREAD

**Issue by KoalaBear84** [ffMathy/Shapeshifter#249]
![image](https://user-images.githubusercontent.com/5886900/39128991-87bfbeb0-4709-11e8-8977-7a42b416107c.png)

The latest release shows that there is a "Virus detected"
https://github.com/ffMathy/Shapeshifter/releases/tag/shapeshifter-v6.2018.0422.2156

The previous release does not:
https://github.com/ffMathy/Shapeshifter/releases/tag/shapeshifter-v6.2018.0422.2150

**Comment by KoalaBear84** [comment]
Lol.. Latest version is 'clean' again:
https://github.com/ffMathy/Shapeshifter/releases/tag/shapeshifter-v6.2018.0423.2163

**Comment by KoalaBear84** [comment]
Maybe check what is changed between v6.2018.0422.2150 and v6.2018.0422.2156, maybe it is as simple as different icons or so.

**Comment by ffMathy** [comment]
That's a false positive. Here's the diff:

https://github.com/ffMathy/Shapeshifter/commit/2cadae7b8e1b81ad3856abaf0dcee9cdef222be0

I think it might be because we push so many updates out or something. It is definitely not infected with a virus.

**Comment by ffMathy** [comment]
@KoalaBear84 the CTRL + V not working, could that be this? https://github.com/ffMathy/Shapeshifter/issues/248

If not, please produce a new issue.
