### ISSUE TITLE
Implement image copying

### ISSUE THREAD

**Issue by ffMathy** [ffMathy/Shapeshifter#25]
Right now, you can't copy images with Shapeshifter (more specifically, device independent bitmaps). It will cause a crash.

**Comment by KoalaBear84** [comment]
What is the path to reproduce?

Create/download a .dib file, copy it in Explorer? Or copy it in Paint?

**Comment by ffMathy** [comment]
Just make an image in paint, select a region of it, and copy it.

**Comment by ffMathy** [comment]
https://github.com/ffMathy/Shapeshifter/blob/master/src/Shapeshifter.UserInterface.WindowsDesktop/Controls/Clipboard/Unwrappers/BitmapUnwrapper.cs

That is where the problem lies - that's where it takes a clipboard handle, converts it into a byte array, and then displays it.

However, now it shows nothing at all. It doesn't crash anymore, but doesn't show anything.

**Comment by ffMathy** [comment]
d135e8fd improves this significantly. Images from paint now show up. The UI is still a mess, and the actual image won't paste either.

**Comment by ffMathy** [comment]
@KoalaBear84 can you help me with this? I can't get the image to paste.

**Comment by KoalaBear84** [comment]
OK, will try to reproduce :)

**Comment by KoalaBear84** [comment]
Just cloned all again, no copy action shows up in the list. Your comment on "Sep 12" says they should show up. But I also know I looked at the problem and found out that it does not unwrap correctly sometimes. #investigating

**Comment by ffMathy** [comment]
Nice. I really appreciate your much needed help.

**Comment by KoalaBear84** [comment]
The hardest part for me is getting to the part where something is happening. Spend 20 minutes, but still not at the part that is processing the image. Your programming skills are great :P

**Comment by ffMathy** [comment]
Thanks :D

I try to follow the SOLID principles. But yes, navigating another persona code base can be rough.

**Comment by ffMathy** [comment]
The unwrappers typically take a pointer generated from the GetClipboardData API and then (based on the format) reads the data as byte array. This is because each format is stored in its own way, and there is no uniform way of handling all clipboard data.

**Comment by KoalaBear84** [comment]
Hah. I just opened the unwrapper file, and at the exact same time, your mail came in :)

When you copy a couple of times just some image region (currently from Paint.NET) it crashes, but does not throw any (CLR) exception, enabled all, but nothing pops up. Could you try to found out why? Thanks.

**Comment by KoalaBear84** [comment]
The bitmap is coming in like "CF_BITMAP", format 2 which is OK. I have to add CF_BITMAP to the `excludedFormats` of the `GeneralUnwrapper.cs`, then the BitmapUnwrapper will pick it up like before. I think that will ring a bell on your side :)

This way it also does not crash. Probably the GeneralUnwrapper does not like bitmaps as I can imagine. The problem is when pasting, the clipboard because corrupt. Sometimes you still have multiple formats (all NULL) in the clipboard after you paste, and sometimes it is completely empty.

So hopefully unwrapping then is OK, but then I guess wrapping it back to clipboard goes wrong.

This could be handy, but maybe you already had something similair. You can also see when you copy something in Paint.NET that you can have custom clipboard types like "PaintDotNet.Rendering.MaskedSurface", learned something new.
http://www.nirsoft.net/utils/inside_clipboard.html

**Comment by KoalaBear84** [comment]
Maybe you can use InsideClipboard for debugging. People can save all info to a .Clp file, and also fully restore the complete clipboard. Works great.

**Comment by KoalaBear84** [comment]
![image](https://cloud.githubusercontent.com/assets/5886900/11349894/07b0a216-922f-11e5-968b-788cef89926b.png)

Hmmmmm. Do you see what I see? Is this something that could be part of the problem? A zero size CF_BITMAP when copying from Paint.NET.

**Comment by ffMathy** [comment]
Wow wow wow good job! And does pasting work as well? Can you make a pull request?

**Comment by KoalaBear84** [comment]
As I remember pasting works good.

I'll try. Still the hardest part, creating pull requests. :P (Yes, I know, I will figure it out) :)

**Comment by ffMathy** [comment]
It is pretty simple. You fork the branch into a new one and then push the changes to that branch. Then go back to GitHub and it will automatically ask if you want to create a pull request for the one you pushed.

**Comment by KoalaBear84** [comment]
Probably fixed with PR #52

**Comment by ffMathy** [comment]
We'll close it for now then. Let's re-open it if it becomes a problem.
