### ISSUE TITLE
Implement health check to prevent fatal crashes

### ISSUE THREAD

**Issue by ffMathy** [ffMathy/Shapeshifter#256]
The build server should launch Shapeshifter with a specific command line parameter to start a healthcheck which will exit with a non 0 exit code if there is an error.

It should trigger a full installation and invoke the installed executable.

**Comment by thegabriestein** [comment]
Should go towards helping solve #248?

**Comment by ffMathy** [comment]
Yes, not only that, but we've also tried a couple of times where I have compiled a build that works on my machine but not other machines.

**Comment by ffMathy** [comment]
This just became relevant again, as now Shapeshifter doesn't seem to want to install. Will focus on this fully.

**Comment by ffMathy** [comment]
This has now been implemented and I'm currently testing it.

**Comment by ffMathy** [comment]
This is now done, and it is working. It is currently finding the bug that is killing the installation.

However, since that bug is already out in the wild, I still need to fix the bug itself. But now at least all of this won't happen again. Closing the issue.
