### ISSUE TITLE
Multiple exes are running in Task Manager

### ISSUE THREAD

**Issue by thegabriestein** [ffMathy/Shapeshifter#264]
Not sure if this is related or duplicate to #262 or #248, but seems like multiple executables are running at the same time. 

![](https://i.imgur.com/YwxI27M.png)

When I just deleted all the Shapeshifter files, and downloaded a fresh exe and opened it, it created the folders and placed the exes etc, but then didn't open the program. And opening the shapeshifter.exe file in Program Files folder doesn't open the software.

And even though Control + V doesn't trigger the software. Multiple Shapeshifter exes are running in Task Manager again. 

Also, without an install manager there isn't a way to clean uninstall the program to make sure the updates are clean.

**Comment by ffMathy** [comment]
This is due to #262. Resolving as soon as possible!

**Comment by thegabriestein** [comment]
Ok awesome, that's what I guessed!

**Comment by ffMathy** [comment]
Aha! This one in particular was due to the EXE files being named different things ("Shapeshifter.exe", "Shapeshifter (1).exe", etc). The duplicate process detection system didn't work for that scenario.

I made it look for the description of the process instead.
