### ISSUE TITLE
Pasting with no items in clipboard causes Shapeshifter to crash

### ISSUE THREAD

**Issue by ffMathy** [ffMathy/Shapeshifter#27]
It should not be possible to even show the UI if there is nothing to show.

In previous versions of Shapeshifter, you couldn't show the UI before at least 2 items were in the clipboard (or else, showing the UI wouldn't make sense anyway). Was this a great idea?

We need help from you (the community) on deciding that.

**Comment by KoalaBear84** [comment]
I would like to always show UI if long pressing CTRL + V, even if there is only 1 item / text. Or no text at all (fresh reboot). Then we can always show "No clipboard items" or so. Then in every situation it is clear what the situation and options are.

**Comment by ffMathy** [comment]
Thanks for your feedback. I agree that showing something in all scenarios would provide a better user experience. I think that's what I'll do.

**Comment by ffMathy** [comment]
This has been fixed in cd84f98f.

**Comment by ffMathy** [comment]
This has been fixed in cd84f98f.
