### ISSUE TITLE
Normal vs clean paste

### ISSUE THREAD

**Issue by thegabriestein** [ffMathy/Shapeshifter#279]
It's great to keep the formatting in many cases when copy and pasting, so Control + V is great. But there are also many circumstances where you want to scrub the formatting from the clipped item, so:
Control + Shift + V = clean paste

**Comment by ffMathy** [comment]
I have closed this since there is now an action for "Paste as plain text".

If you still think this is a good idea, we should instead open a ticket where it is possible to assign hotkeys to specific types of actions.
