### ISSUE TITLE
There's no going back after UI is opened

### ISSUE THREAD

**Issue by szepeviktor** [ffMathy/Shapeshifter#281]
While keeping Ctrl+V pressed there is no way to cancel pasting - if someone does not find the appropriate item something must get pasted.

Would it be possible to add a cancel button or `X` sign to the UI?

**Comment by thegabriestein** [comment]
Same thing I thought haha, actually already solved here #255, works really well!

**Comment by szepeviktor** [comment]
Could you point that out in the README?
@ffMathy

**Comment by szepeviktor** [comment]
@thegabriestein Thanks!!

**Comment by szepeviktor** [comment]
Pressing the right arrow once makes the UI disappear.

Was it in the top left corner??

**Comment by szepeviktor** [comment]
No!

**Comment by ffMathy** [comment]
Alright, perfect - just wanted to make sure :+1:

**Comment by szepeviktor** [comment]
Cloud you tell me what is the function of the right arrow key?

**Comment by ffMathy** [comment]
Well, left and right swaps between the action pane (on the left) and the clipboard item pane (on the right). 

After swapping, you can use up and down arrows to navigate, and then release CTRL + V to perform the action specified.

However, sometimes you're in the middle of copying something and you want to cancel it. By default when holding down CTRL + V, you are in the clipboard items pane. Here, a "right arrow key" will cancel the pasting.

Similarly, if you had already hit "left arrow key" to go to the action pane, an additional "left arrow key" would cancel the pasting.

Does that make sense?

**Comment by ffMathy** [comment]
Oh, and if you like my support and also the software, consider donating a dollar on Patreon. That would really help a lot! Every little donation matters, and you are only charged every time a maaaaajor update hits.

**Comment by szepeviktor** [comment]
Thank you.
I consider donating.

It would be nice to have this information in the README.

**Comment by ffMathy** [comment]
Yes, I will add it soon to the newly launched website here: https://ffmathy.github.io/Shapeshifter :+1:
