### ISSUE TITLE
Design tweaks

### ISSUE THREAD

**Issue by ffMathy** [ffMathy/Shapeshifter#282]
- Minus margin the clipboard list by 1 pixel in the top.
- Gradient veil for clipboard list is too intense and/or too big.
- Source should always align to bottom.
- There should always be space enough for two lines of text.
- The veil for the screen should fade in.

**Comment by ffMathy** [comment]
Veil fade will be excluded.

Two lines of text is still being resolved.

Everything else is done.

**Comment by ffMathy** [comment]
Actually, I'll open new for the two remaining things if I decide they are important.

**Comment by thegabriestein** [comment]
@ffMathy The background shadow is kind of bugging me, I know it's to signal that the overlay is open, but it just darkens the thing you're trying to paste into, and if you triggered it on purpose, you already expect it to be there and work. It's better than it was before (lighter now), but still seems unnecessary and obstructs the work you're doing in the background.

**Comment by thegabriestein** [comment]
That works, 1% should be fine. Maybe add setting for “allow mouse actions” which could hide the overlay? And could the overlay be 0% or RGBA? 

Not a huge deal, just seems like doesn’t need to actually be visible?

**Comment by ffMathy** [comment]
I would rather have consistency than have that as a setting. The settings should be at a bare minimum to keep the simplicity up.

Try with 1%. If it still bothers you, re-open the ticket :+1:

It has been set to 1% now 😄 

By the way, that gray color is depressing me. If you could select your own color other than re-using the Windows 10 color, would you do it? :smirk:

Because that would be a good idea for an issue too then.

**Comment by thegabriestein** [comment]
True, keeping consistency and settings smaller is better when possible. 1% will probably be fine. 

Haha, yeah the gray is really clean on my setup because of transparency and window colors. Would definitely love a simple box for setting the theme color like on v5, although I had v5 set to #ffffff, so I really just prefer it to be really clean and simple.
