### ISSUE TITLE
A referral was returned from the server

### ISSUE THREAD

**Issue by kyle-charlton** [ffMathy/Shapeshifter#288]
Hi!
I tried to install shapeshifter-v6.2018.0425.2281 for testing, but after running the install file, the program does not run.
I have tried a few times to install whenever you sent out a new release, but it never seems to want to run.
I went to the program folder and tried to start the program that way but I get an error message "A referral was returned from the server".

I'm a web developer and do not know much about software development, but the logs say something about "Cannot find the certificate and private key for decryption". 

I'll attach the snapshot of the error message and the log file.
![error-message](https://user-images.githubusercontent.com/12102133/39269154-ed7722ce-4886-11e8-94ce-b1a5f2d00141.JPG)
[Shapeshifter.log](https://github.com/ffMathy/Shapeshifter/files/1948593/Shapeshifter.log)

**Comment by KoalaBear84** [comment]
See #254, I've had the same problem. Still want to look into it. Didn't know about the good logging then.

**Comment by ffMathy** [comment]
Very interesting! Thank you so much for trying Shapeshifter.

A few questions:
1. Is it a work machine or something where Active Directory is enabled?
2. Do you have any antivirus software running?

**Comment by kyle-charlton** [comment]
I'm running Windows Defender and I do have XAMPP installed, I also have Ditto installed as well, not sure if that would throw any conflicts or not.

**Comment by KoalaBear84** [comment]
I also have XAMPP installed, don't know if that is related, as there is only a single version that is having this problem.

**Comment by ffMathy** [comment]
Hmmm. @KoalaBear84 do you also get that error in your logs?

The error in the logs is at least related to the certificate Shapeshifter is installing on your machine upon launch. This certificate is auto-generated and random every time, and ensures that it has permissions to hook into the keyboard and take dominance over things like Remote Desktop and TeamViewer.

**Comment by KoalaBear84** [comment]
I've now used Fiddler, but it does not really show anything as it looks like. No new entries, only sometimes, which might be from another tool that is running.

There is NO log file created, really. Or no single file. (You can easily check this with [Everything](https://www.voidtools.com/) and sort on Date Modified. Also GREAT tool to look for files)

**Comment by KoalaBear84** [comment]
Still wasn't finished, but I send my work-in-progress comment above in advance so you see that there isn't even a logfile created here.

THIS is what happens, should have something to do with "consent.exe":
![image](https://user-images.githubusercontent.com/5886900/39287054-ed967390-4921-11e8-90a4-e88a39b7f070.png)

**Comment by KoalaBear84** [comment]
It looks like it does have something to do with trying to run as Administrator:
https://www.repairwin.com/fix-a-referral-was-returned-from-the-server-error/
https://social.msdn.microsoft.com/Forums/windowsdesktop/en-US/8f19b0ba-cb14-4081-8622-c3b3a6481e48/application-fails-to-start-under-vista-a-referral-was-returned-from-the-server-manifest?forum=windowsgeneraldevelopmentissues

_I got by this problem by changing the "uiAccess" parameter from "true" to "false."  I have another, smaller program where the manifest with uiAccess="true" works with no problem.  Apparently, this has something to do with the "User Account Control: Only elevate UIAccess applications that are in secure locations" option in secpol.msc._

**Comment by ffMathy** [comment]
Hmmmm! Very interesting!

What is your UAC setting at right now? Is the UAC dialog disabled? The one that asks if you really want to run things as administrator?

I have that setting enabled in my `secpol`. Do you?

**Comment by KoalaBear84** [comment]
![image](https://user-images.githubusercontent.com/5886900/39287525-6b76a918-4924-11e8-8e4c-7c580cc2aea1.png)
![image](https://user-images.githubusercontent.com/5886900/39287583-ab185652-4924-11e8-866f-52bfc82ceb34.png)

**Comment by ffMathy** [comment]
Hmmm our UAC settings are the same, but not the security policy. What happens if you enable that policy?

**Comment by ffMathy** [comment]
Wait, that's not the right policy you are looking at.

**Comment by ffMathy** [comment]
The right one is "User Account Control: Only elevate UIAccess applications that are in secure locations" according to your source.

**Comment by KoalaBear84** [comment]
I've enabled it, tried to start it again, still the same issue.

BUT, it is only happening with this version I think:
![image](https://user-images.githubusercontent.com/5886900/39287637-f38844ce-4924-11e8-98df-786839a20d8d.png)

**Comment by ffMathy** [comment]
In `C:\Program Files\Shapeshifter` what happens if you remove the `.manifest` file, and launch it again?

**Comment by KoalaBear84** [comment]
Also tried UAC on least secure. Still the same problem.

Excellent question! Wanted to try that myself. :P

IT WORKS, without the manifest!

**Comment by ffMathy** [comment]
Alright, then I think I know what is going on. I will investigate the issue.

I still can't explain why it's only happening to you guys.

Is your Windows fully updated?

That manifest is important - it is what makes it possible for Shapeshifter to work on top of full-screen applications in Windows 8. But I guess we could probably remove it since that's no longer a concern.

**Comment by KoalaBear84** [comment]
![image](https://user-images.githubusercontent.com/5886900/39288587-dfe1446c-4928-11e8-9abe-60643985b92a.png)

**Comment by ffMathy** [comment]
This has been resolved and will be in the next release. There, the `uiAccess` attribute in the manifest will be `false`, which should be enough.

**Comment by KoalaBear84** [comment]
Saw the commit.

I see this problem is something else:
https://support.techsmith.com/hc/en-us/articles/203728788-Camtasia-Windows-A-referral-was-returned-from-the-server

Here they are talking about the thing you now changed, uiAccess.

**Comment by thegabriestein** [comment]
I have my UAC turned down by the way because of the annoying popups that have never once been for something bad haha.

**Comment by KoalaBear84** [comment]
OK, couldn't this be a single version problem as specified in this comment above:
https://github.com/ffMathy/Shapeshifter/issues/288#issuecomment-384519642

**Comment by KoalaBear84** [comment]
It's my Home computer, it was a clean Windows 10, never really changed security settings this time.

I don't have the problem with any other version except this executable, and only when the manifest file is there. I know the manifest is 'inside' the executable, embedded, and Windows check it also embedded to show the "Gaurd" icon on it so you can see it wants to start like Administrator for example. There should not be a seperate manifest file?

**Comment by ffMathy** [comment]
Hmmm but can you then confirm that? Can you try a previous version?

**Comment by KoalaBear84** [comment]
Running perfectly fine, tried two old version:
https://github.com/ffMathy/Shapeshifter/releases/tag/shapeshifter-v6.1.2089
https://github.com/ffMathy/Shapeshifter/releases/tag/shapeshifter-v6.2018.0422.2130

**Comment by ffMathy** [comment]
Well that's good, we should be able to narrow it down by looking at the diff then. Can you help with that perhaps?

**Comment by KoalaBear84** [comment]
Compared shapeshifter-v6.2018.0422.2130 and shapeshifter-v6.2018.0423.2167 and there are NO source code changes between those too. I have no idea what should be the problem.

If you also do not have a clue, close this ticket and move on. Maybe the only real problem is the Code signing certificate.

**Comment by ffMathy** [comment]
Alright, closing. Runtime based certificate creation and signing will go away soon in favor of #302, where I will actually buy a true code signing certificate.
