### ISSUE TITLE
Error copying text

### ISSUE THREAD

**Issue by KoalaBear84** [ffMathy/Shapeshifter#29]
I don't know how to else communicate besides Github. I do have Hangouts or Telegram.

Synced repo and checked. I see that the Core project is gone now. Whatever I do, copying does not work. Get different errors, which I CANT copy / paste, probably because of exception Shapeshifter in VS :D

Error when copying some text:
No matching constructor found on type 'Shapeshifter.UserInterface.WindowsDesktop.Converters.ByteArrayToImageSourceConverter'. You can use the Arguments or FactoryMethod directives to construct this type. Line number '11' and line position '57'.

Unfortunately the code is too complicated for me because everything is an interface and with DI etc.

**Comment by ffMathy** [comment]
Github is fine! Wow man. I really appreciate you joining in on the project and trying to build it. However, right now I am working on some major refactoring. Although the project compiles, it doesn't work.

I typically work on Shapeshifter twice a day and to avoid losing my work, I push whatever I have to the repository when I need to get off the bus to/from work.

I realize I should be better at pushing things when they are ready after seeing this, so I apologize for the mess. I'll get the project fixed soon and not push in the future unless everything fully works.

Thanks for all your energy and drive. You have helped tremendously already.

**Comment by KoalaBear84** [comment]
OK, I'll understand. Will wait till then and continue.

Thanks for working on it, I really appreciate it! :)

**Comment by ffMathy** [comment]
Alright, it should now work both in the designer of Visual Studio and the build itself. I'll now do my best to not push anything else until I have tested that everything works. Thanks for the effort.
