### ISSUE TITLE
Hard crash after trying to change settings menu

### ISSUE THREAD

**Issue by thegabriestein** [ffMathy/Shapeshifter#297]
When v6.2018.0425.2303 launches the first time clean after install, and going into the settings menu to it change the default timing, if you type in "150" you can't type past "1" before it crashes (assuming it's too low a value?). 

It then throws a crash warning popup saying to check logs and then upon reopening, it will instant crash upon opening the settings menu. And when I go to look for the logs I can't find any where they should be.

It can be reopened and seem to function fine, but opening the settings will keep crashing it.

**Comment by ffMathy** [comment]
Wow, that's critical. 

What do the logs say? Should be easy to reproduce though.

Shapeshifter gets its settings from the %LOCALAPPDATA%\Shapeshifter folder. Try wiping that clean.

**Comment by ffMathy** [comment]
Fixed.
