### ISSUE TITLE
Install issues, probably prevented by anti-virus

### ISSUE THREAD

**Issue by thegabriestein** [ffMathy/Shapeshifter#298]
Upon fresh installing 6.2018.0425.2303, anti-virus picked it up and potentially broke the install? It didn't notify of successful install, and didn't auto-launch after finishing. Similar to #249? Logs say that it was unable to install keyboard dominance watcher like in #274 (accidentally deleted the logs in the folders when reinstalling though, sorry).

It also placed these DLLs in the downloads folder even though the program was able to be launched through Program Files, and even after deleting the dlls the program seems to run still:

![](https://i.imgur.com/sJOFtnU.png)

I also tested reinstalling, and it still places the dlls in the downloads folder where I downloaded it. Fairly certain they shouldn't be going there and should be going to Program Files or Temp at least.

Some more things UX wise:
1. How to avoid virus detection issues somehow? Ask for permission before install? Seems like it interrupted install for sure timing wise when installing.
2. Need a desktop shortcut at least, that's created after the successful install, which should be an easy solution to launching the solution again if it crashes (vs full installer with start menu etc).

**Comment by thegabriestein** [comment]
After trying to fresh install, now I can't get the exe to silent install at all. Had to go into task manager to close the process as well as delete the folders and then reopen the install exe and now it's functioning again.

Here's the log for it though:

`[12280] 2018-04-25 02:19:48.205 [ERR] Could not install the keyboard dominance watcher injection mechanism into the Global Assembly Cache.
System.IO.FileNotFoundException: The given assembly "Shapeshifter.WindowsDesktop.KeyboardHookInterception.dll" ("C:\Users\offic\Downloads\Shapeshifter.WindowsDesktop.KeyboardHookInterception.dll") does not exist.
   at EasyHook.Config.Register(String InDescription, String[] InUserAssemblies)
   at Shapeshifter.WindowsDesktop.Services.Keyboard.KeyboardDominanceWatcher.Install()
[12280] 2018-04-25 02:19:48.263 [VRB] Launching C:\Program Files\Shapeshifter\Shapeshifter.exe under verb runas in C:\Program Files\Shapeshifter with arguments cleanup "C:\Users\user\Downloads\Shapeshifter.exe".
[12280] 2018-04-25 02:19:48.836 [INF] Launched installed executable.
[12280] 2018-04-25 02:19:48.836 [VRB] All command line arguments have been processed. Argument processor will trigger termination.
[12280] 2018-04-25 02:19:48.836 [VRB] Startup preparation operation completed.
[12280] 2018-04-25 02:19:48.836 [VRB] The startup preparation operation signaled a termination request. Will quit process.`

**Comment by KoalaBear84** [comment]
Ah, them I'm not the only one who still has installation problems. Also experienced the extra dll's in my Download folder, I thought it might be from previous installation things, but looks like it still happens.

You can also dynamically load the DLL's without having to install them anywhere. I always do that like this:
1. Add the reference to the "Files" section of the Resources file
2. It will automatically remove ".dll" from it and will replace a dot with an underscore
3. Put "Assembly_" before it
4. Add this code to Program.cs
```static class Program
{
    /// <summary>
    /// The main entry point for the application.
    /// </summary>
    [STAThread]
    static void Main()
    {
        Application.EnableVisualStyles();
        Application.SetCompatibleTextRenderingDefault(false);

        // Add this line
        AppDomain.CurrentDomain.AssemblyResolve += CurrentDomain_AssemblyResolve;

        Application.Run(new FrmMain());
    }

    static Assembly CurrentDomain_AssemblyResolve(object sender, ResolveEventArgs args)
    {
        string assemblyName = args.Name;

        assemblyName = assemblyName.Substring(0, assemblyName.IndexOf(","));
        assemblyName = assemblyName.Replace('.', '_');
        assemblyName = $"Assembly_{assemblyName}";

        // .NET 4.0+
        if (assemblyName.EndsWith("resources"))
        {
            return null;
        }

        object dllobject = Resources.ResourceManager.GetObject(assemblyName);

        if (dllobject != null)
        {
            byte[] dll = (byte[])dllobject;
            return Assembly.Load(dll);
        }

        MessageBox.Show($@"Could not resolve Assembly ""{args.Name}""!", Application.ProductName, MessageBoxButtons.OK, MessageBoxIcon.Error);

        return null;
    }
}```

**Comment by ffMathy** [comment]
@KoalaBear84 I am already doing that using `Costura.Fody`. That's what makes Shapeshifter able to run as a single executable :+1:

Those files present are needed because `EasyHook` actually needs to run the files, and install them into the Global Assembly Cache. `EasyHook` is what makes it possible to take control over CTRL + V when Remote Desktop and TeamViewer etc is being used. This was why #274 and #208 used to occur.

What antivirus software are you using?

We could prevent it from killing Shapeshifter if we got ourselves a code signing certificate. But that stuff is expensive 😢

**Comment by KoalaBear84** [comment]
I'm using the Windows 10 built it Windows Defender.

**Comment by ffMathy** [comment]
I have Windows Defender disabled. I'll try enabling it to see if that will change anything.

**Comment by ffMathy** [comment]
Just noticed those files were put in the downloads folder. They are supposed to go into Program Files. This has been fixed.
