### ISSUE TITLE
Revise installation system

### ISSUE THREAD

**Issue by ffMathy** [ffMathy/Shapeshifter#301]
The installation/update system should be revised entirely due to the recent errors constantly popping up. `InstallArgumentProcessor` should be explicit.

1. Launch Shapeshifter with no arguments.
2. Is it running from installed directory? If no, launch again with `install` arguments.
3. Is it running as admin? If not, run again with same arguments (`install`).
4. Copy to Program Files folder.
5. Start installed version with `cleanup` arguments.
6. Clean up.
7. Start itself with no arguments.

**Comment by ffMathy** [comment]
Yeah it's very buggy. Should probably also use explicitly wait every time until a process has closed.

**Comment by szepeviktor** [comment]
How about an old-school installer with windows and buttons?

**Comment by ffMathy** [comment]
I still like the concept of a portable process better. That way, it is also easier to customize and update. But don't worry, we will have a setup wizard sooner or later :+1:

**Comment by beppe9000** [comment]
It seems the installation has to be done because of the overlay feature needs the EXE file to be started from the program files directory (when not run as administrator, right?).

Could you link me to some documentation about this? Google only yelds android stuff.

**Comment by ffMathy** [comment]
Here: https://msdn.microsoft.com/en-us/library/windows/desktop/ee671610(v=vs.85).aspx

> To use UIAccess, an assistive technology application needs to:
> - Be signed with a certificate to interact with applications running at a higher privilege level.
> - Be trusted by the system. The application must be installed in a secure location that requires a user account control (UAC) prompt for access. For example, the Program Files folder.
> - Be built with a manifest file that includes the uiAccess flag.

**Comment by ffMathy** [comment]
Without it, Shapeshifter also has to run as administrator to be able to work on applications that do not run as administrator. Does that make sense?

**Comment by beppe9000** [comment]
ok i understand now, so you can display a "install?" dialog with yes (do the current install method) and no (relaunch as administrator to run in portable mode)

**Comment by ffMathy** [comment]
Yes, except portable mode is still not possible that way.

There are other reasons Shapeshifter needs to be installed. One of them being that it needs to use `EasyHook` (which requires assemblies registered in the Global Assembly Cache) to make Shapeshifter work for remote desktop.

Of course we could just notify the user that that won't work if they decide to do a portable installation.

**Comment by beppe9000** [comment]
Yeah I think a portable mode with limitation should be useful. For example most of the utilities I use are kept on a separate drive and kept between windows installs.

Looking at the EasyHook's feature list it seems it doesn't actually require registering to the GAC.
![image](https://user-images.githubusercontent.com/6625123/39406743-c158b634-4bbb-11e8-9191-f32f864b2037.png)

**Comment by ffMathy** [comment]
Hmmm that thing with `EasyHook` not requiring GAC looks very interesting! I'll be sure to give that a try.

**Comment by beppe9000** [comment]
Maybe it does handle the registerning for you...

**Comment by ffMathy** [comment]
I think it does, but registration to the GAC needs files to be on disk, which is why this needs more investigation. Thank you for your help so far though!

**Comment by beppe9000** [comment]
I'm glad to hear that. I hope portabl is implemented soon.

**Comment by ffMathy** [comment]
It seems to me you have some development experience yourself. Do you feel like joining? Pull requests are welcome, and I can guide you in the right direction.

Also, feel free to join us on the Gitter chat https://gitter.im/ffMathy/Shapeshifter.

And while you're at it, if you like my super-fast response times and the effort I put into Shapeshifter, consider donating on Patreon here: https://www.patreon.com/flamefusion

**Comment by ffMathy** [comment]
Fixed.
