### ISSUE TITLE
Updating Shapeshifter 5 to 6

### ISSUE THREAD

**Issue by ffMathy** [ffMathy/Shapeshifter#306]
Potentially if we re-purchased the domain `flamefusion.net`, we could actually get the Shapeshifter 5 clients to install version 6. Definitely worth trying out! There are tens of thousands of users still on Shapeshifter 5.

**Comment by KoalaBear84** [comment]
Hmm, did you abandoned / expired it. Now they will ask $ 1000 or $1500+ for it. Wasn't FlameFusion also your own company name?

**Comment by ffMathy** [comment]
Yes it was. Now I want to do things under my own name though.

**Comment by ffMathy** [comment]
Hmmm yes I see it has been bought. Probably impossible then.
