### ISSUE TITLE
Copy command sometimes ignored

### ISSUE THREAD

**Issue by thegabriestein** [ffMathy/Shapeshifter#309]
v6.2018.425.2307 seems to be the most stable and normal yet! However it does have a small issue where it seems like it's not actually retaining what I right click and copy, or Control + C. And then when I go to paste, it pastes normally, but the actual content pasted is an older item.

I've tested and made sure it's happening consistently on any site or program. The build is slightly old (latest release is v6.2018.0426.2331), but other than that it seems to working fine.

**Comment by ffMathy** [comment]
I need exact steps to reproduce. Which application are you copying from, and which are you copying to?

**Comment by ffMathy** [comment]
Also, what are you copying and pasting?

**Comment by thegabriestein** [comment]
Seems like any program, to any program. And any type of data, primarily text. I first noticed it in Chrome, where I started to specifically test it by highlighting text, Control + V, and then checking the list and noticing it wasn't shown and therefore makes sense why it was pasting one of the older items in the list that I just copied before.

**Comment by ffMathy** [comment]
Aha, I see. Seems to be introduced in #168. Will fix shortly.

**Comment by ffMathy** [comment]
Fixed.

**Comment by thegabrielstein** [comment]
I've tested and made sure it's happeningI've tested and made sure it's happening
I've tested and made sure it's happeningI've tested and made sure it's happening

**Comment by thegabrielstein** [comment]
I've tested and made sure it's happening
