### ISSUE TITLE
Display how many items in the clipboard for that application when copying

### ISSUE THREAD

**Issue by ffMathy** [ffMathy/Shapeshifter#311]
When copying something from (for instance) Photoshop (hitting CTRL + C), we should display a number for 1 second in the upper right corner, showing how many items that have been copied from that application.

That will help people remember that Shapeshifter is active, and that they can copy more things if they wish.

This is part of the coaching in #284 and #310.

**Comment by thegabriestein** [comment]
Hmm the notifications should be gentle, not more than maybe once a day maybe? Might be a good influence though to remind people, especially within a window I think, maybe a 30 second window?

**Comment by ffMathy** [comment]
Alright, this has been resolved.

**Comment by ffMathy** [comment]
Please give some feedback on it :+1:
