### ISSUE TITLE
Hold CTRL + C could miss clipboard items

### ISSUE THREAD

**Issue by KoalaBear84** [ffMathy/Shapeshifter#32]
When you hold down CTRL + C you will receive many clipboard updates.

I had a situation this morning that it would skip multiple handles, which looks like always increase by 5 (ohh, only for text I see).

Now I selected the Debug output directory files of ShapeShifter and hold down CTRL + C.

Output:
Information: Clipboard update message received with sequence #3435.
Information: Clipboard update message received with sequence #3449.
Information: Clipboard update message received with sequence #3463.
Information: Clipboard update message received with sequence #3477.
Information: Clipboard update message received with sequence #3491.
Information: Clipboard update message received with sequence #3503.
Information: Clipboard update message received with sequence #3671.
Information: Clipboard update message received with sequence #3671.
Information: Clipboard update message received with sequence #3671.
Information: Clipboard update message received with sequence #3671.
Information: Clipboard update message received with sequence #3671.
Information: Clipboard update message received with sequence #3671.
Information: Clipboard update message received with sequence #3671.
Information: Clipboard update message received with sequence #3671.

This is not a very important problem I guess. Maybe, if it's possible, this can be fixed by using some sort of queue. But I don't know if the previous clipboard item / handle is still available. Then the queue could be processed in the background.

**Comment by ffMathy** [comment]
Is this actually causing you problems?

**Comment by KoalaBear84** [comment]
I don't think it really is a problem. I did notice it as a finding.

Probably also less of a problem with the new regex.

**Comment by ffMathy** [comment]
It's important only to fix things that are real issues and won't be a problem with performance. In the future though, we will need to avoid duplicate copies of data if possible.
