### ISSUE TITLE
Windows Server 2016 App Crash

### ISSUE THREAD

**Issue by beppe9000** [ffMathy/Shapeshifter#321]
I'm going to report this crash here.

I copied a bunch of strings and then proceeded to do CTRL-V, hold it and then select a previous clipboard with the arrows. This resulted in a crash. It was the first time I run the application.

Afterwards I noticed it automatically moved itself to the program files folder and deleted itself from my download path. I think this is a programming error, it should ask before "installing" itself.

Anways I run it again with admin priviledges but it wouldn't do the popup when I copied something and crashed again.

The log file is in this pastebin, I hope it helps.

https://pastebin.com/raw/F07bZLNE

**Comment by ffMathy** [comment]
As for the installation part, we are working on an installation wizard in #301 and #17.

It needs to install itself into the `Program Files` folder in order to be able to overlay itself on top of applications running as administrator.

As for the log, that's highly interesting. I will create a new prerelease version with more logging to help diagnose the issue, as the current report is not enough unfortunately.

I'll keep you posted.

**Comment by ffMathy** [comment]
Alright, I have introduced more logging. I will let you know when there is a release you can try again. It won't solve the issue, but it will improve the logging so that your new log will be able to diagnose it better.

Once again thanks for reporting this issue!

**Comment by beppe9000** [comment]
Ok, I will try with that once it is ready. I think the second crash was not logged, even tough I saw the error report dialog multiple times.

About the installation I really wouldn't mind a simple yes/no dialog explaining what is going on before acting.

**Comment by ffMathy** [comment]
Hmmm very good point in terms of the installation stuff. We don't necessarily need a wizard - we can just start with informing the user what happened.

**Comment by ffMathy** [comment]
Try using the latest prerelease version now, and see if it reports anything better in the logs.

**Comment by beppe9000** [comment]
I tried [this one](https://github.com/ffMathy/Shapeshifter/releases/tag/shapeshifter-v6.2018.429.2411).
It has not yet crashed. Before running it I removed the previous shapeshifter files from the system, but did not clean the registry (i don't even know if it is used).

There is something wrong, tough. I saw some problems:
 - Multiple pastes with the same CTRL-V press
 - Pasting a string then pasting the actual clipboard
 - Pasting multiple copies of the same clipboard
 - Pasted "v" after pasting a string.
 - randomly failed to load long CTRL-V press instead it pasted a lot of times.

I caught the last one in a  GIF: https://i.imgur.com/GNA7MKO.gifv


<hr> Also, I found two crash dumps from before I can send them if you find them useful (i don't know how to use them despite having some programming experience as an hobby).
<hr>

Edit: Actually it crashed silently during the GIF recording

**Comment by ffMathy** [comment]
Alright, it seems it is having issues inserting unicode text into the clipboard. Where did you copy the text from? Notepad++?

As for the other bugs, can you catch them on video too perhaps?

**Comment by beppe9000** [comment]
I did all the tests in notepad++.
I don't know if Notepad++ converts files to unicode, but this is what the file looks like in hex:
![image](https://user-images.githubusercontent.com/6625123/39410929-297d7cf6-4c00-11e8-9227-58f98983d9b6.png)

The rest of the bugs happened all almost at the same time before the crash. It was all in that single session so maybe they are logged too? Anyways I will setup continuous screen recording for that.

What about the dmp files ^? You need those?

Is there a build guide or I just load the SLN in vs and let it build? I'll try to debug it _in vivo_.

**Comment by ffMathy** [comment]
You just load the SLN in latest Visual Studio. No magic needed.

Even though Notepad++ doesn't store the file in Unicode, it still seems to add that format to the clipboard. I'll investigate soon.

**Comment by beppe9000** [comment]
I caught on GIF both the double pasting and the `v` after the pasted string. Afterwards when navigating with the arrow keys it skipped words as if the CTRL was still pressed down.

![this](https://i.imgur.com/95Zmubl.gif)

**Comment by ffMathy** [comment]
You are awesome. Thank you for these great reports. Will look at it probably this Tuesday or Wednesday.

**Comment by ffMathy** [comment]
Double pasting will now be tracked in #359. Leaving this issue open for the rest of the problems.

**Comment by KoalaBear84** [comment]
Maybe test it with the newest version @beppe9000

**Comment by beppe9000** [comment]
It seems to work 90%. Yeah! Since the last update I experienced no unexpected crash (notepad++ tested ✓), double pasting or keystroke failure and that's great. 

I just noticed that when shapeshifter is running I can not paste from my image editor (paint shop pro) to electron apps. :\
Screenshots made with PrtScrn work, tough. Maybe the clipboard data is not relayed correctly?

log here: https://pastebin.com/raw/296Pgz28

**Comment by KoalaBear84** [comment]
Good to hear. I guess it is the same problem as #407

**Comment by beppe9000** [comment]
I looked at the log and it seems psp uses its own clipboard format i think. 

<br>

I also found a sweet spot in the delay mechanism that cancels the paste keystroke.
To reproduce end the CTRL-V a nanosecond before the overlay shows.

**Comment by beppe9000** [comment]
I want to report that Shapeshifter doesn't register the global hotkey every once in a while, and that there is still some condition that makes the CTRL key become stuck after pasting.

**Comment by ffMathy** [comment]
Yes we have improved logging to try to nail down the bug. Automatic error reports make it easier. Give it some time, we have not forgotten this issue.

**Comment by ffMathy** [comment]
Can you try the latest prerelease now?

**Comment by beppe9000** [comment]
Sorry I was on vacation these days. I downloaded the latest prerelease (https://github.com/ffMathy/Shapeshifter/releases/tag/shapeshifter-v6.2018.606.2854).

When I double click the exe file I get an AppHang error wether I run as administrator or not...

What files and/or registry key do I need to remove to "unistall" the previous version?

**Comment by ffMathy** [comment]
There is a known issue with this. Clear your Program files folder first then run it.

**Comment by beppe9000** [comment]
alright i will report asap

**Comment by beppe9000** [comment]
I've done that but I still get the app hang

**Comment by KoalaBear84** [comment]
And if you delete the whole `C:\Program Files\Shapeshifter` folder? For me it worked after this.

**Comment by beppe9000** [comment]
i did
