### ISSUE TITLE
Paste more than once, in one go

### ISSUE THREAD

**Issue by KoalaBear84** [ffMathy/Shapeshifter#33]
I sometimes need 5 lines with the same, so I do CTRL + C, and then 10 times CTRL + V, V, V, V, V.

This currently is not supported and you get the following:
Information: Paste hotkey message received.
Information: Paste combination duration mediator ignored paste hotkey because the paste combination was already held down.

It would be nice if this is supported. And maybe with an option if the current functionality needs to also be supported.

**Comment by ffMathy** [comment]
That's a great suggestion from you as always Koala! I'll implement that soon.

**Comment by ffMathy** [comment]
This is a tricky situation. More tricky than I had imagined.

Right now, we have a `PasteCombinationDurationMediator` which takes care of how long the CTRL+V (paste combination) is held down. The underlying mechanism is that we use the `RegisterHotkey` function to block CTRL+V in the system, and then send us a `WM_HOTKEY` message when that combination is held down.

Once we receive that message, we wait in the background until the combination is released. When it is released, the `ClipboardPasteService` is instructed to perform the paste operation. It does this by *disabling* that hotkey mechanism, then simulating a CTRL+V press, and then enabling the hotkey mechanism again (since there is no other way of simulating a paste in Windows).

But once we hold down CTRL+V, then release V, we don't get a `WM_HOTKEY` message again if we press V again (while still holding down CTRL). Both keys have to be released first, for the event to occur.

**Comment by ffMathy** [comment]
And by "disabling the hot key mechanism" I mean that the paste service calls UnregisterHotkey and then RegisterHotkey again after the paste.

**Comment by ffMathy** [comment]
I think I will focus on this issue again soon. It must be possible to solve, and is very important. Any help would be nice.

**Comment by ffMathy** [comment]
This has now been resolved! Awesome! #89 should fix this.

**Comment by ffMathy** [comment]
Damnit, this is still not solved. And it introduced the bug #92 as well.
Oh well, it solves it in some scenarios.

I will need to look more into the rest of the cases.

**Comment by ffMathy** [comment]
Here is a dump of the relevant pieces of the log when it happens.

```
   Information: Firing PasteCombinationReleased event.
   Information: Message received: [25299488, WM_SHOWWINDOW, 0, 0]
   Information: Consumer count incremented to 1.
   Information: Spawning consumption thread.
     Information: Consumer count decremented to 0.
     Information: Consuming item.
       Information: Passing message WM_SHOWWINDOW to interceptor PasteHotkeyInterceptor.
       Information: Passing message WM_SHOWWINDOW to interceptor KeyInterceptor.
       Information: Passing message WM_SHOWWINDOW to interceptor ClipboardCopyInterceptor.
     Information: Stopping consumer loop.
   Information: Firing AfterPasteCombinationReleased event.
   Information: Clipboard package has been injected to the clipboard.
   Information: Simulating paste with CTRL down and V released.
   Performance information: Started executing SimulatePaste.
   Information: Disabled paste hotkey interceptor.
   Information: Uninstalled paste hotkey interceptor.
   Information: Sending key combinations [V: Down], [V: Up], [LeftCtrl: Up].
   Information: Installed paste hotkey interceptor.
   Information: Sending key combinations [LeftCtrl: Down].
   Information: Enabled paste hotkey interceptor.
   Performance information: Finished executing SimulatePaste in 40.0284 milliseconds.
   Information: Paste simulated.
   Information: Paste action performed.
   Information: Message received: [25299488, WM_CLIPBOARDUPDATE, 4, 0]
   Information: Consumer count incremented to 1.
   Information: Spawning consumption thread.
     Information: Consumer count decremented to 0.
     Information: Consuming item.
       Information: Passing message WM_CLIPBOARDUPDATE to interceptor PasteHotkeyInterceptor.
       Information: Passing message WM_CLIPBOARDUPDATE to interceptor KeyInterceptor.
       Information: Passing message WM_CLIPBOARDUPDATE to interceptor ClipboardCopyInterceptor.
       Information: Clipboard update message skipped.
     Information: Stopping consumer loop.
   Information: Consumer count decremented to 0.
   Information: Consuming item.
   Information: Paste combination duration loop has ticked.
   Information: Firing PasteCombinationReleased event.
   Information: Firing AfterPasteCombinationReleased event.
   Information: Clipboard package has been injected to the clipboard.
   Information: Simulating paste with CTRL down and V released.
   Performance information: Started executing SimulatePaste.
   Information: Disabled paste hotkey interceptor.
   Information: Uninstalled paste hotkey interceptor.
   Information: Sending key combinations [V: Down], [V: Up], [LeftCtrl: Up].
   Information: Installed paste hotkey interceptor.
   Information: Sending key combinations [LeftCtrl: Down].
   Information: Enabled paste hotkey interceptor.
   Performance information: Finished executing SimulatePaste in 42.5332 milliseconds.
   Information: Paste simulated.
   Information: Paste action performed.
   Information: Stopping consumer loop.
 Information: Message received: [25299488, WM_CLIPBOARDUPDATE, 4, 0]
 Information: Consumer count incremented to 1.
 Information: Spawning consumption thread.
   Information: Consumer count decremented to 0.
   Information: Consuming item.
     Information: Passing message WM_CLIPBOARDUPDATE to interceptor PasteHotkeyInterceptor.
     Information: Passing message WM_CLIPBOARDUPDATE to interceptor KeyInterceptor.
     Information: Passing message WM_CLIPBOARDUPDATE to interceptor ClipboardCopyInterceptor.
     Information: Clipboard update message skipped.
   Information: Stopping consumer loop.
```

**Comment by ffMathy** [comment]
The `AfterPasteCombinationReleased` event is triggered twice. It is the event that is responsible for actually pasting.

**Comment by ffMathy** [comment]
Thanks to @Eraknelo, this has now been resolved.
