### ISSUE TITLE
Can't trigger the overlay or paste in v6.2018.429.2389 

### ISSUE THREAD

**Issue by thegabriestein** [ffMathy/Shapeshifter#333]
Current experience status:
Auto update seems to work well, possibly first time at least that I've noticed it functioning (doesn't seem like it's stayed current in the past). The UI seems fairly fast and snappy. The cleaned action list is very helpful. The And the small charm for copying items is really clean. 

But the first time I opened the computer with the update, the keybind trigger was unresponsive in opening the overlay. After closing the program, and reopening it, it seems to function now.

The log says:
2018-04-29 13:34:26.070 [#11004] [Shapeshifter.WindowsDesktop.Services.Processes.ProcessManager] [VRB]
Launching explorer under verb null in  with arguments "C:\Users\-\AppData\Local\Temp\Shapeshifter".

**Comment by ffMathy** [comment]
I am currently working on auto-reporting which will help resolve this issue, but I'll leave it open for reference. Also #321 has some really cool repro details I will work on that might fix it too.

**Comment by ffMathy** [comment]
Try 6.2018.429.2430 when it is live in a few minutes. Should auto-report findings.

**Comment by ffMathy** [comment]
Closing in favor of #339, which is a more detailed auto-report of this exact scenario.
