### ISSUE TITLE
Crash log, KeyNotFoundException

### ISSUE THREAD

**Issue by KoalaBear84** [ffMathy/Shapeshifter#334]
This was after the installation failed and I placed it myself in the right directory.

v.6.2018.429.2389

[Shapeshifter20180429.log](https://github.com/ffMathy/Shapeshifter/files/1959554/Shapeshifter20180429.log)

**Comment by KoalaBear84** [comment]
Ahh, almost created a new issue, but saw it was the same.

Tried the newest build v6.2018.429.2416. Installation didn't work, copying and starting didn't work. No logs created.

Deleted C:\Program Files\Shapeshifter and tried again, no luck. It starts, it says "Shapeshifter is ready" and it disappears, no logs.

Ahh, logs on new location? (C:\Users\username\AppData\Local\Temp\Shapeshifter\Shapeshifter20180430.log)

[Shapeshifter20180430.log](https://github.com/ffMathy/Shapeshifter/files/1959579/Shapeshifter20180430.log)

**Comment by ffMathy** [comment]
Try 6.2018.429.2430 when it is live in a few minutes. Should auto-report findings.

**Comment by ffMathy** [comment]
Perhaps it causes a crash that is so fatal that the whole application crashes hard.

Will investigate.

**Comment by ffMathy** [comment]
Do the logs say something about that it is trying to report the issue?

**Comment by KoalaBear84** [comment]
No, the last thing is `An unhandled error occured.`, so that's also the reason why, unhandled.

**Comment by ffMathy** [comment]
Yes but if it's able to log it, it should also be able to report it.

Anything in Fiddler? Any traffic to the Shapeshifter website for reporting?

**Comment by ffMathy** [comment]
I think it is because the reporting is asynchronous. Will look into it soon.

**Comment by ffMathy** [comment]
Made an attempt at resolving it here: https://github.com/ffMathy/Shapeshifter/pull/335

**Comment by ffMathy** [comment]
Works! #336! Will close this one instead.
