### ISSUE TITLE
Image copying does not work for BI_RGB

### ISSUE THREAD

**Issue by KoalaBear84** [ffMathy/Shapeshifter#34]
If bV5Compression is 0 / BI_RGB (Uncrompressed) the stride becomes 0 and new Bitmap() command in CreateDrawingBitmapFromPointer fails.

More info here:
https://msdn.microsoft.com/en-us/library/windows/desktop/dd183381%28v=vs.85%29.aspx

Path to reproduce:
1. Install Greenshot
2. Take a screenshot
3. Copy to clipboard from displayed context menu

Low prio :)

**Comment by ffMathy** [comment]
Duplicated in https://github.com/ffMathy/Shapeshifter/issues/25.
