### ISSUE TITLE
2+ line items aren't using the 2 available preview lines

### ISSUE THREAD

**Issue by thegabrielstein** [ffMathy/Shapeshifter#341]
Seen here:

![](https://i.imgur.com/hl6clfG.png)

For whatever reason, you can see the double pasted Imgur screenshot url from ShareX (I know you're already talking about a fix for that in chat), but the multiple paragraph text block I copied only uses 1 line of preview, when it would be nice to have 2-3 even (and there's space for it).

**Comment by ffMathy** [comment]
So just to elaborate. From Chrome to Chrome for instance?

**Comment by thegabrielstein** [comment]
Yeah, copying will add it to the clipboard assuming that it's not frozen (#339 I think, fixed by exiting the tray and reopening the exe). But then anytime I open the overlay, it only shows one line of preview.

**Comment by ffMathy** [comment]
I think this has something to do with the font used.

Can you find a text that (when copied) always produces this result?

**Comment by ffMathy** [comment]
Although I've seen this issue before I can't reproduce it now, and I tried with all kinds of different text combinations. I need a string of text that will produce this consistently.

**Comment by ffMathy** [comment]
@thegabrielstein?

**Comment by thegabrielstein** [comment]
Well that's weird and good haha, as of 513.2683 it's suddenly working properly now. Wasn't working up until this point. So could be either direct troubleshooting fixed it, or an indirect action solved it. Copying one of the paragraphs of text from the previous issue comments on the page above (a random quick test of real world content source) properly utilized both lines for preview.

**Comment by ffMathy** [comment]
All good! Will close for now then :+1:

**Comment by ffMathy** [comment]
I was able to reproduce this again. I think it may be due to non-breaking spaces though, so I should be able to reproduce soon!

https://docs.microsoft.com/en-us/dotnet/framework/xaml-services/whitespace-processing-in-xaml

**Comment by ffMathy** [comment]
Non-breaking space replacement has been added. Let me know if this still happens - I can no longer reproduce it.
