### ISSUE TITLE
Automated issue reports improvements

### ISSUE THREAD

**Issue by ffMathy** [ffMathy/Shapeshifter#344]
In #226 we added automatic issue reports. Very useful indeed, but we still need a few things.

- Using `details` to hide all log messages in a pane that is collapsed per default: https://github.com/dear-github/dear-github/issues/166#issuecomment-252282315
- Showing 1000 log entries per default.
- Including verbosity in log messages.
- Always including 1000 log entries, get rid of the `Stack<T>` and use an alternative.
- HTML encode log contents to avoid accidental tagging. Instead of an at-sign, use `&commat;` (&commat;).

**Comment by thegabriestein** [comment]
Definitely need to protect privacy in the logs and automated reporting. Primarily by removing any personally identifiable information (especially the machine username!). But also as much as possible in what was copied, when it was copied, where it was copied from and where it was pasted to etc.

**Comment by ffMathy** [comment]
As much as I would like to log the data itself that people copy and what window they copy to/from, I think that would be a privacy violation too.

What if we report the process though? For instance `chrome.exe` instead of `PornHub - Chrome`?

**Comment by ffMathy** [comment]
Fixed. Also anonymized the general log input. As for storing what applications store the data, so far it has not been needed - I will add more logging as it becomes important.
