### ISSUE TITLE
"Get Updates" instead of "Search for Updates"

### ISSUE THREAD

**Issue by thegabriestein** [ffMathy/Shapeshifter#346]
Instead of "search", should call it "get", and that by clicking that, it automatically just updates it to the newest version. Maybe that's how it's designed already, but for whatever reason it doesn't act that way and doesn't seem to want to auto update, and it's already behind versions. Would be nice to one-click update.

**Comment by ffMathy** [comment]
It will update to the latest version if there is a newer available. Are you sure it's not simply because the newer releases are pre-release versions?

You need a pre-release version to update to a pre-release version. Install a pre-release manually.
