### ISSUE TITLE
Performance issues Regex

### ISSUE THREAD

**Issue by KoalaBear84** [ffMathy/Shapeshifter#35]
As found in #30, the regex is probably not meant to be runned on large texts.

We could use a simpler regex to just extract the URLs, and validate the Url's outside of regex.

    public static bool CheckURLValid(this string source)
    {
        Uri uriResult;
        return Uri.TryCreate(source, UriKind.Absolute, out uriResult);
        OR
        return Uri.TryCreate(source, UriKind.Absolute, out uriResult) && uriResult.Scheme == Uri.UriSchemeHttp;
    }

P.s., I haven't tested the results against the table on https://mathiasbynens.be/demo/url-regex

This could be done multithreaded, but that maybe is overkill and even bad for the performance, maybe only if you have thousands of links in your clipboard text.

**Comment by ffMathy** [comment]
Using an URI would require a very specific format for the URL. Furthermore, it would require that the URL starts with `http://` which is not very good for text. I expect the users to write URLs like `google.com`, and we'll still need to support it.

To make things worse, there are custom TLDs on the web like `.tech`, `.google` that also need to be supported, and new ones constantly arrive.

The current regular expression indeed has a chance of timing out, but if you use it with a leading `http://` then it no longer times out.

I think we should instead try to tweak the existing regular expression to see if that will work, or use one from the link above that is less precise, but still recognizes most URLs.

**Comment by ffMathy** [comment]
6a0e3da5 resolves this issue. Please let me know if you still have performance issues. The same regular expression is used, but I made some optimizations.
