### ISSUE TITLE
Don't show patrons that want to be anonymous

### ISSUE THREAD

**Issue by ffMathy** [ffMathy/Shapeshifter#353]
On the website, we show patron supporters even if they have set in their profile that they don't want to share their pledges publically.

**Comment by ffMathy** [comment]
Reported this as an issue here: https://github.com/Patreon/patreon-php/issues/38

Let's hope they respond and have a solution.

**Comment by ffMathy** [comment]
Doesn't look like Patreon wants to fix this.

**Comment by ffMathy** [comment]
Will re-open if new stuff happens.

**Comment by KoalaBear84** [comment]
Ahh, I understand. Because it uses the same official API, and because of the official GitHub. Especially with GDPR / AVG they should take care of it.
