### ISSUE TITLE
Cannot paste in Elevated process

### ISSUE THREAD

**Issue by KoalaBear84** [ffMathy/Shapeshifter#36]
It looks like I cannot paste inside an elevated process. Don't know if this was also the case in v4, haven't used it for long time.

Notepad++ is running with Administrator rights. But Shapeshifter, which is started by Visual Studio is not, because VS is not started with admin rights.

I cannot paste inside Notepad++ when Shapeshifter is running. Which I think is somewhat strange as Shapeshifter is only emulating a CTRL + V. But maybe this way it has something to do that you cannot send Windows Messages to an elevated process, when your own process is not elevated.

There are many more problems like this is software on Windows. It's not high priority, but a thing to keep in mind and test.

**Comment by ffMathy** [comment]
Shapeshifter 4 had this very same problem. There is no way to get around it I'm afraid. UAC (User Account Control) is there for a reason, and protects you from dangerous software.

I suggest you avoid launching Notepad++ as an administrator. Is there any reason you needed this in the first place?

**Comment by ffMathy** [comment]
I just revived this issue.

I found this. https://social.msdn.microsoft.com/Forums/en-US/b68a77e7-cd00-48d0-90a6-d6a4a46a95aa/sendinput-fail-beause-interface-privilege-isolation-uipi-and-integrity

Apparently it is indeed possible, but it requires signing with a level 1 certificate, which is expensive.

**Comment by ffMathy** [comment]
This solves is solved by https://github.com/ffMathy/Shapeshifter/issues/38.
