### ISSUE TITLE
Use NGen

### ISSUE THREAD

**Issue by ffMathy** [ffMathy/Shapeshifter#372]
Run NGen on compiled executables for higher performance.

**Comment by ffMathy** [comment]
Awaiting question response here: https://stackoverflow.com/questions/50157338/embedding-a-resource-in-a-net-framework-assembly-after-compilation?noredirect=1#comment87335427_50157338

**Comment by ffMathy** [comment]
Now that installation system has been revised, this is possible.

I expect the memory usage to drop significantly and the performance of startup and general snappiness to increase radically too.

**Notes to self:**
`csproj` of the project is now embedded within the executable itself. Through that, I should be able to emit all embedded Costura DLL references to disk upon installation, and then run `ngen.exe` on the main executable. Costura should also be switched to runtime initialization.

**Comment by ffMathy** [comment]
Removal of `csproj` did not necessarily help. Something else must be causing the error. Should take a look at the first breaking commit.

**Comment by ffMathy** [comment]
Alright, all dependencies are now deployed upon installation.

ngen still complains. I think it might be because costuras configuration file must be changed to runtime first.

**Comment by ffMathy** [comment]
This article will probably help.

https://blogs.msdn.microsoft.com/jianges/2012/08/09/how-to-troubleshoot-ngen-issues/

**Comment by ffMathy** [comment]
This is now done! However, I need help testing that existing builds can update to this one without crashing.

@KoalaBear84? @thegabrielstein? @SmartManoj?

**Comment by SmartManoj** [comment]
ngen  shapeshifter installing window is opened and runs indefinitely.
To have Installing Percentage should be nice

**Comment by ffMathy** [comment]
Thanks @SmartManoj, I think this has been resolved now.
