### ISSUE TITLE
Shapeshifter process ending immediately after start

### ISSUE THREAD

**Issue by thejoshtaylor** [ffMathy/Shapeshifter#374]
Downloaded v6.2018.429.2389 exe file and whenever I attempt to start it, the initial notification and the icon appear, but the process is ends immediately after. Attached is the .log file recorded with the issue.

[Shapeshifter20180503.log](https://github.com/ffMathy/Shapeshifter/files/1972665/Shapeshifter20180503.log)

**Comment by KoalaBear84** [comment]
Duplicate of https://github.com/ffMathy/Shapeshifter/issues/345

Please download the newest version and try again. 😃

**Comment by thejoshtaylor** [comment]
@KoalaBear84 Issue is still present. After deleting old Shapeshifter folders in both Program Files and Temp and redownloading the latest .exe, I still get the same issue.

**Comment by ffMathy** [comment]
Will investigate!

**Comment by ffMathy** [comment]
@KoalaBear84 was right. It is a duplicate. The reason you are seeing this is because you are on the latest "stable" build which has this problem, but the latest pre-release build (see "releases") has this problem fixed.
