### ISSUE TITLE
Embed manifest in executable

### ISSUE THREAD

**Issue by ffMathy** [ffMathy/Shapeshifter#377]
Now that #302 is done, we can embed the manifest file into the executable (perhaps with `mage.exe`). This can make the installation procedure less tedious and less error-prone.

**Comment by KoalaBear84** [comment]
Hmm, isn't this the default? I have the [Koala Shortcut Arrow](https://koalabear.nl/software.phphttps://koalabear.nl/software.php) tool, and it also show the "Administrator" prompt, without an external .manifest file.

**Comment by ffMathy** [comment]
Perhaps! Will investigate!

**Comment by ffMathy** [comment]
@KoalaBear84 you were right! Fixed.

**Comment by ffMathy** [comment]
@KoalaBear84 now I remember why I didn't do it. `uiAccess=true` doesn't work if you want to debug via Visual Studio. Switching back to deployment of manifest at runtime.

**Comment by ffMathy** [comment]
Fixed.
