### ISSUE TITLE
Does not open

### ISSUE THREAD

**Issue by SmartManoj** [ffMathy/Shapeshifter#385]
shapeshifter-v6.2018.504.2495
Os : win10 x64

**Comment by ffMathy** [comment]
Did you copy more than 1 item in your clipboard since you started Shapeshifter?

**Comment by SmartManoj** [comment]
I freshly download the app. When i install it does not show anything.The previous versions will have a tray icon.

**Comment by SmartManoj** [comment]
Runs after running the file in %LOCALAPPDATA%
