### ISSUE TITLE
I might do something wrong

### ISSUE THREAD

**Issue by szepeviktor** [ffMathy/Shapeshifter#39]
- v5.0.0.107 on Windows 10 Pro 64 bit Hungarian
- I have to hold down Ctrl and `V` also to get the clipboard list displayed, the list disappears when releasing `V` (and the last item get pasted)
- the language dropdown is empty or Chinese no matter what I've selected previously
- in external mode in the clipboard item's taskbar context menu the Shapeshifter icon flashes and disappears
- coloring works

Please advise.

**Comment by szepeviktor** [comment]
Maybe v.5.0.0.107 is very old.
v5.0.0.1474
- has no UI or tray icon
- cannot paste images

**Comment by ffMathy** [comment]
Yeah I just bumped this repository's Shapeshifter to version 6, because it is actually a complete rewrite of the old one, which caused confusion. Shapeshifter 6 is in alpha right now, and isn't feature complete. Can you make separate issues for the other missing features?

**Comment by szepeviktor** [comment]
The only blocking one:

> I have to hold down Ctrl and V also to get the clipboard list displayed, the list disappears when releasing V (and the last item get pasted)

But #43

**Comment by ffMathy** [comment]
But that is how it is supposed to work. What did you have in mind instead?

**Comment by szepeviktor** [comment]
:smile: I mean while holding down <kdb>Ctrl</kbd> the list disappears. It only *flashes-in* when <kbd>V</kb> is pressed.

**Comment by ffMathy** [comment]
Does that also happen for Shapeshifter 6?

**Comment by szepeviktor** [comment]
I don't know, I am waiting for binary.

**Comment by ffMathy** [comment]
Try https://github.com/ffMathy/Shapeshifter/releases/tag/shapeshifter-v6.0.0.1511

**Comment by ffMathy** [comment]
Any progress?

**Comment by szepeviktor** [comment]
This is the output:
![ss2](https://cloud.githubusercontent.com/assets/952007/11634375/5396728c-9d10-11e5-988a-186272348a4d.jpg)

**Comment by ffMathy** [comment]
Can you try with the latest release as well that just came out a few minutes ago?

**Comment by szepeviktor** [comment]
Thank you! It work normally.

But I am not able to use it daily without the *hitting V cycles through clipboard items* feature.
Could you add that in the next binary?

**Comment by ffMathy** [comment]
Well the thing is that it is not currently in the current version of Shapeshifter (version 5). And how will this work? When hitting V multiple times, Shapeshifter 5 already just double-pastes.

**Comment by szepeviktor** [comment]
Just think of <kbd>V</kbd> as hitting the down arrow while holding Ctrl.

**Comment by ffMathy** [comment]
But this can't work if you still want double pasting to work. Sorry.
