### ISSUE TITLE
KeePass

### ISSUE THREAD

**Issue by szepeviktor** [ffMathy/Shapeshifter#40]
I think Shapeshifter conflicts with KeePass.
KeePass is able to type your login name and password, but not when Shapeshifter is running.

**Comment by ffMathy** [comment]
Interesting. I'll see if I can replicate the issue later.

**Comment by ffMathy** [comment]
@szepeviktor can you retry this with the latest version and see if it is still an issue?

**Comment by KoalaBear84** [comment]
Steps how it should be reproduced, but I can't.

1. Have an account in KeePass
2. Go to application where it needs to be 'entered' and select Username field
3. Do CTRL + V inside KeePass

I cannot reproduce this.

Yes. I'm still onboard of ShapeShifter... Unfortunately no time yet. Luckily we have another one on board which already contributes great! Hope to have some time soon.

**Comment by ffMathy** [comment]
That's fine @KoalaBear84. We all have our breaks once in a while. Can't wait for you to get back again!
