### ISSUE TITLE
Quiet mode (hide notifications and alerts)

### ISSUE THREAD

**Issue by SmartManoj** [ffMathy/Shapeshifter#400]
Settings to hide notification counter

**Comment by ffMathy** [comment]
Very interesting. What is it about the counter that bothers you? Could you perhaps instead make the counter more transparent? Is it in the way?

**Comment by ffMathy** [comment]
I still need clarification. Feedback is very important, so that [programming by permutation](https://en.wikipedia.org/wiki/Programming_by_permutation) is avoided. 

Shapeshifter is intended as a premium piece of software, so I want to make sure I understand the reason behind @SmartManoj's request.

If Apple listened to all of their users without looking at the reasoning, their products would have become bloated as well.

**Comment by SmartManoj** [comment]
I feel the Notifacation Counter is a distraction

**Comment by ffMathy** [comment]
Aha! So you are not bothered by the window that shows the amount of items you have copied @SmartManoj?

**Comment by ffMathy** [comment]
I removed the "Shapeshifter is ready" notice. Presence of the tray icon should be enough. Closing this issue unless there were other notifications you wanted to remove :+1:

**Comment by SmartManoj** [comment]
@ffMathy Yes I am bothered by the notifcation counter

**Comment by ffMathy** [comment]
Alright. What is it about it that bothers you? Is it because it is overlapping something? Can you try to describe it? There might be a better solution than just hiding it.

**Comment by SmartManoj** [comment]
When something pop ups, our mind and work gets distracted,

**Comment by SmartManoj** [comment]
Since we use copy frequently , it is better to have an option to hide the counter.Since we didn't do anything with the number

**Comment by ffMathy** [comment]
But if the number is not there, are you actually aware that you can use Shapeshifter to paste stuff? Won't you forget to use it?

**Comment by SmartManoj** [comment]
The programming is running from the startup itself, I am well known awared .

**Comment by KoalaBear84** [comment]
We offcourse are. If you could make a checkbox, "Quiet mode" with tooltip "Hides copy notification counter" or something like that, and do an if (!quietMode) { ShowNotification(); } it would be OK

I know too many options is not good, but I thing it is a good one to have.

**Comment by ffMathy** [comment]
Alright, perfect! I will make an option for it and then leave it on per default.

Thanks for the feedback! :+1:

**Comment by thegabrielstein** [comment]
Yeah single checkbox that hides or shows everything is perfect. And leave it on by default. A lot of good use cases like when screen sharing, screen recording, or presenting and you don't want to distract people.

**Comment by ffMathy** [comment]
Ah that's a perfect use case Gabriel! Didn't think of that!

**Comment by ascott23** [comment]
@ffMathy do you need someone to work on this?

**Comment by ffMathy** [comment]
That would be so cool! Pull requests are always welcome!

**Comment by ffMathy** [comment]
Fixed by @ascott23! Thanks!
