### ISSUE TITLE
Don't encode HTML characters

### ISSUE THREAD

**Issue by KoalaBear84** [ffMathy/Shapeshifter#406]
![image](https://user-images.githubusercontent.com/5886900/39689985-da2d9f94-51d8-11e8-8ab8-18b00dc83989.png)

Don't encode the HTML characters, maybe because of WPF?

**Comment by ffMathy** [comment]
This is because applications that copy `Rich Text Format` data into the clipboard is then converted to HTML and then text by Shapeshifter.

When that happens, the value is encoded. I need to decode it.

Nice catch!

**Comment by KoalaBear84** [comment]
I see it also happens with spaces, or it looks more line a new line from Wordpad, not Word.

![image](https://user-images.githubusercontent.com/5886900/39690861-cebc8d8e-51db-11e8-98ea-f8418ce8a19e.png)

**Comment by ffMathy** [comment]
Fixed.
