### ISSUE TITLE
cannot paste on remote environment

### ISSUE THREAD

**Issue by Jheronymus** [ffMathy/Shapeshifter#41]
Hi
I just installed version 5.0.0.107 from the main website. I like it, but I just noticed that I can copy from a remote environment to my local, but I cannot paste on the remote using the CTRL+V shortcut. Hitting it once doesn't do anything. Long pressing shows the shapeshifter clipboard list, but selected items aren't pasted either.
Copy-pasting from the remote to the local machine works though.
Using CTRL+C and richt-click-paste still works on the remote environment.

Hope this helps. Love that this truly enhances this CTRL+V and that it doesn't break normal operation. Except for this case that is.

Additional info: I use windows 7 Proffesional SP1, 64bit. The remote is opened via a Jetro Cockpit 4 client. The remote system runs windows server 2008 R2 SP1 64bit

**Comment by ffMathy** [comment]
Is this through Microsoft Terminal Services (regular remote desktop), or some third party app?

**Comment by szepeviktor** [comment]
Yes, RDP.

**Comment by Jheronymus** [comment]
Hi, sorry for not getting back to you earlier. I've checked it again using windows terminal services and that works. So I guess this related to Jetro Cockpit app. http://jetroplatforms.com/products/cockpit4-application-delivery/
Somehow the CTRL+V combo gets blocked when using shapeshifter with the Jetro cockpit remote desktop. If you close shapeshifter, you can just copy-paste to the remote environment.

**Comment by ffMathy** [comment]
This will be resolved in #129.
