### ISSUE TITLE
 Feature Requests : Amount of Memory to use

### ISSUE THREAD

**Issue by SmartManoj** [ffMathy/Shapeshifter#419]
Like No of items to hold, Amount of memory to use option because if we copy 10 large files the system gets hanged.

**Comment by ffMathy** [comment]
Can you add steps to reproduce? Can you send me some files I can try to copy that has this problem?

This is indeed a good idea. Perhaps we should put the files on disk if they are way too large.

**Comment by SmartManoj** [comment]
Not only files but also some 2000 lines of text cause this

**Comment by ffMathy** [comment]
I don't get that issue. Can you attach a file that does this when its contents are copied?

**Comment by SmartManoj** [comment]
Task Manager
![image](https://user-images.githubusercontent.com/7231077/39705983-94534532-522d-11e8-8e27-ed891bf84fee.png)
After i randomly copied some folders , paste shortcut not works but from context menu.
![image](https://user-images.githubusercontent.com/7231077/39706035-b86472b6-522d-11e8-9cde-3ec294e07550.png)

**Comment by ffMathy** [comment]
Can you attach a zip file containing the files you are copying to reproduce this?

**Comment by ffMathy** [comment]
I agree with @KoalaBear84. Resolving that issue will also solve this.
