### ISSUE TITLE
Long-press delete to clear all items

### ISSUE THREAD

**Issue by SmartManoj** [ffMathy/Shapeshifter#425]
It is nice to have a command like restart or empty clipboard

**Comment by ffMathy** [comment]
You can hit the delete button on your keyboard to delete individual items. Is that good enough?

**Comment by SmartManoj** [comment]
To delete items in UI it is nice to have a pin button to avoid long pressing

**Comment by ffMathy** [comment]
Hmmm, what about if holding down the delete keyboard for 1 second would erase the whole list. Would that work for you?

**Comment by SmartManoj** [comment]
Yeah its working

**Comment by ffMathy** [comment]
Alright, then I will leave this issue open until that has been implemented.

**Comment by SmartManoj** [comment]
Long pressing empty the clipboard now itself

**Comment by thegabrielstein** [comment]
I'm worried about deleting clipboard items accidentally. Like how holding down the backspace buttons on iOS devices can go from character-by-character, to word-by-word and it can be very easy to delete more than intended. I think the speed of delete should be constant. Set to whatever the key repeat speed of the user's machine is?

Maybe the tray icon context menu could have an option for "Clear clipboard history"?

**Comment by ffMathy** [comment]
I was thinking of holding down for like 3 seconds to delete everything at once, not one at a time. Would that work too?

**Comment by thegabrielstein** [comment]
3 seconds would probably work. I think still some risk if the user doesn't know about that functionality and can't undo it. I would vote for a "Clear history" menu item in the tray, but either one probably works.

**Comment by ffMathy** [comment]
If he doesn't know about it, he would never hold it down, would he?

**Comment by ffMathy** [comment]
Actually, I just noticed that holding it down already works. Closing this issue for now.
