### ISSUE TITLE
Start failure on Win10 Pro

### ISSUE THREAD

**Issue by szepeviktor** [ffMathy/Shapeshifter#43]
v6 stack trace

![stack-trace](https://cloud.githubusercontent.com/assets/952007/11019707/68c646a4-8605-11e5-9540-5c9fac5c322c.jpg)

I hope you understand it without Hungarian knowledge.

**Comment by ffMathy** [comment]
Thanks. This happened because I bumped the version number to 6, which caused a new version to be automatically released, without binaries because the build server couldn't run the build. I'll solve it so it won't happen again. My bad.

**Comment by szepeviktor** [comment]
Thank you.
Will it be called 6.0 or 5.2?

**Comment by ffMathy** [comment]
Yes I didn't rename the milestones yet. It will be 6.

**Comment by ffMathy** [comment]
This has been fixed in b3d8511e.

**Comment by szepeviktor** [comment]
Thank you.
Is a new binary available?

**Comment by szepeviktor** [comment]
v6.0.0.1510
The process starts, I can copy&paste the regular one-clipboard way but there is no UI visible.

**Comment by szepeviktor** [comment]
I think I have to wait.

**Comment by ffMathy** [comment]
Yes, I will let you know when a new version is available. Sorry about htat.

**Comment by ffMathy** [comment]
Try this release: https://github.com/ffMathy/Shapeshifter/releases/tag/shapeshifter-v6.0.0.1511

**Comment by szepeviktor** [comment]
It works :smile: !
