### ISSUE TITLE
Doesn't respect pinning

### ISSUE THREAD

**Issue by ffMathy** [ffMathy/Shapeshifter#430]
Pinned items aren't in the top.

**Comment by KoalaBear84** [comment]
Would also be good to have a "Pinned" label/icon, or a slightly darker color.

**Comment by ffMathy** [comment]
Very good idea!

**Comment by ffMathy** [comment]
Fixed pinning. Will open an additional story for the pin icon.

**Comment by thegabrielstein** [comment]
Awesome! Yeah the lack of visual differentiation meant I thought it wasn't working even if it was haha. Very good idea to add a small icon or something when it's pinned.
