### ISSUE TITLE
Shapeshifter domains sometime fail to load

### ISSUE THREAD

**Issue by KoalaBear84** [ffMathy/Shapeshifter#455]
**Describe the bug**
The website does not respond. I got this multiple times over multiple days.

**To Reproduce**
Go to https://shapeshifter.software or https://shapeshifter.app

**Expected behavior**
The actual website.

**Screenshots**
![image](https://user-images.githubusercontent.com/5886900/39968038-e15d091a-56c6-11e8-9b88-8c7bb6a1bb21.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome

**Comment by ffMathy** [comment]
Very nice report, and I am aware of the issue. I think it's GoDaddy that is having issues, but will confirm.

**Comment by KoalaBear84** [comment]
OK, I thought it was something with IIS recycling at first, but it looks like it is indeed a deeper problem.
Both are pointing to other IP addresses.

shapeshifter.app [159.25.16.133]
shapeshifter.software [184.168.221.21]

**Comment by ffMathy** [comment]
That's expected. `shapeshifter.app` is hosted at `joker.com`, and `shapeshifter.software` is hosted at `godaddy.com`.

I think I will transfer them to Google Domains or something if possible to see if that helps.

**Comment by ffMathy** [comment]
Oh, and I should add that they are set as "URL forwards".

**Comment by ffMathy** [comment]
This is so strange... It's a simple URL forward. I'm starting to think GitHub is actually the culprit.

**Comment by KoalaBear84** [comment]
I tried to find the GitHub URL, but couldn't find it, was something with shapeshifter.github.io?

**Comment by ffMathy** [comment]
ffmathy.github.io/Shapeshifter 😊

Thanks for helping out.

**Comment by KoalaBear84** [comment]
Thanks. It is seriously a very strange problem.

I've tried it on my own PC and through work laptop with VPN, so with multiple providers and browsers (Chrome and FireFox), but I cannot load it, and I have no clue about it.

I've tried multiple sites which check for DNS things..
http://dnscheck.pingdom.com/?domain=shapeshifter.app
https://mxtoolbox.com/SuperTool.aspx?action=dns%3ashapeshifter.app&run=toolpage

I've tried multiple website screenshot sites which all work..
https://snapito.com/
https://web-capture.net/
https://www.url2png.com/

**Comment by KoalaBear84** [comment]
But you do get the .software one to work? Always? Sometimes?

It could be that they are too new, it could also be because of HSTS, which I see is not used in the website. Where is it hosted? And how does it work in combination of github.io? Is it only some DNS record you can use from GitHub?

Maybe you need the HSTS, as the app domain requires it, and maybe it is getting in the way and not redirection or so.

ASP.NET Core 2.0:
https://neelbhatt.com/2018/02/04/enforce-ssl-and-use-hsts-in-net-core2-0-net-core-security-part-i/
https://www.softfluent.com/blog/dev/Improve-the-security-of-your-website-using-SSL-and-HSTS-with-ASP-NET-Core

ASP.NET Core 2.1 (built in):
https://blogs.msdn.microsoft.com/webdev/2018/02/27/asp-net-core-2-1-https-improvements/
https://docs.microsoft.com/en-us/aspnet/core/security/enforcing-ssl?view=aspnetcore-2.1&tabs=visual-studio

I don't know IF it is the case, but it would be good anyway to upgrade to 2.1 and use HTTPS / HSTS.

**Comment by ffMathy** [comment]
It is hosted on github pages. Actually, what is in the docs folder is what is there.

The domain itself i assume is hosted on joker.com and godaddy.com, who then probably host the URL forwarding.

**Comment by ffMathy** [comment]
I have made some changes to the setup that could maybe work. Let's give it some time.

**Comment by KoalaBear84** [comment]
It looks like now also the github site is redirecting to shapeshifter.app, so now nothing works 😇

**Comment by thegabrielstein** [comment]
Very weird! Shapeshifter.software has been working well for me in the recent past. But now gives me this:

![](https://i.imgur.com/ZEuGQQm.png)

**Comment by KoalaBear84** [comment]
Yes, it's because of these changes I think:
https://github.com/ffMathy/Shapeshifter/commit/2d89b9ba9654dc9544c86925cc3186feb8c8226c
https://github.com/ffMathy/Shapeshifter/commit/e9e8a6e61f27e5321a3251dbf359e6533bd00d9d

**Comment by ffMathy** [comment]
Yeah I am experimenting a bit with it.

**Comment by ffMathy** [comment]
https://help.github.com/articles/troubleshooting-custom-domains/

This will probably fix it. Will look into it when I get home.

**Comment by ffMathy** [comment]
It seems https://shapeshifter.app/ is now running perfectly after the latest fixes. Since these are not URL forwards but A records, they will run very stable.

I am closing the issue. It might take a few hours for this to be seen on your end too.

As for "shapeshifter.software", I will leave it to die :smile:

**Comment by KoalaBear84** [comment]
At home it does NOT work, still the same error.

At work I get a little more, maybe it will work later:
![image](https://user-images.githubusercontent.com/5886900/40050831-e3129a40-5838-11e8-8670-a84263163dce.png)

**Comment by ffMathy** [comment]
It seems to work fine for me now. I think it just needs some more time. I also had those issues at first.

**Comment by KoalaBear84** [comment]
You might be able to include it into the Shapeshifter.Website project and host it where it is currently hosted. And hopefully get this to work correctly with the shapeshifter.app domain, and maybe use a Let's Encrypt SSL certicicate.

**Comment by ffMathy** [comment]
Alright, domains pointed to Azure. Still need to merge #470 for this to get fixed though.

**Comment by KoalaBear84** [comment]
Great. It is now working without any problems. Works on work laptop, smarthpone, desktop PC. Also tested on FireFox. All OK.

**Comment by KoalaBear84** [comment]
Any idea why it takes so long before the first image is displayed?

**Comment by ffMathy** [comment]
Nice! Feel free to make a PR! If you jump to the Develop branch, you can edit directly in GitHub and it will make a PR for you.

**Comment by KoalaBear84** [comment]
Done

**Comment by ffMathy** [comment]
Awesome! Thanks!
