### ISSUE TITLE
System.DllNotFoundException: Unable to load DLL 'EasyHook64.dll' in v6.2018.513.2683

### ISSUE THREAD

**Issue by KoalaBear84** [ffMathy/Shapeshifter#457]
**Describe the bug**

**To Reproduce**
1. Windows + R
2. "mstsc"
3. Without doing anything it crashed

**Desktop (please complete the following information):**
Microsoft Windows [Version 10.0.14393]

**Additional context**
[Shapeshifter20180513.log](https://github.com/ffMathy/Shapeshifter/files/1998563/Shapeshifter20180513.log)

I was trying to test #129 / #441

**Comment by KoalaBear84** [comment]
#129

**Comment by KoalaBear84** [comment]
OK, it does this when mstsc.exe is open, also after a restart. I does not happen when I have my own 'ActiveX' RDP control and probably also not with others like https://mremoteng.org/

With my own RDP tool holding down CTRL + V it does not work, it does not take control, it just does paste it over and over again like without Shapeshifter. That is another issue which I will try after this one.

I do use the auto updater this time, but I think it is not related.

**Comment by ffMathy** [comment]
Did this also happen for the latest stable release?

**Comment by KoalaBear84** [comment]
Yes, it also happens with https://github.com/ffMathy/Shapeshifter/releases/tag/shapeshifter-v6.2018.513.2683

**Comment by KoalaBear84** [comment]
The latest NOT pre-release is v6.2018.513.2683 which is the reported one. Also happens with v6.2018.513.2696 and also with an older v6.2018.501.2448

**Comment by ffMathy** [comment]
I have a theory... Did you start Shapeshifter from `C:\Program Files\Shapeshifter` when this happened or not?

**Comment by KoalaBear84** [comment]
Yes, from the normal path.

**Comment by ffMathy** [comment]
Alright. Then I should be able to reproduce easily :+1:

**Comment by ffMathy** [comment]
Is the file present in the installation directory - `EasyHook64.dll`?

**Comment by ffMathy** [comment]
Fixed.

**Comment by ffMathy** [comment]
It will no longer crash, but it may still produce a warning in the logs. At least you can continue using it now.
