### ISSUE TITLE
More instances of the exe could be started

### ISSUE THREAD

**Issue by szepeviktor** [ffMathy/Shapeshifter#46]
Not a singleton application.

**Comment by ffMathy** [comment]
This is fixed/improved in 8c61b271 (I think). Let me know if that's not the case.

**Comment by szepeviktor** [comment]
Thank you.

**Comment by szepeviktor** [comment]
Please see http://www.codeproject.com/Articles/4430/Single-Instance-Application-in-C
needs quick registration
