### ISSUE TITLE
Mozilla Firefox Crashed

### ISSUE THREAD

**Issue by SmartManoj** [ffMathy/Shapeshifter#463]
When pasting screenshot from clipboard ,mozilla crashed when shapeshifter is on

**Comment by ffMathy** [comment]
This is critical. Do you agree @thegabriestein?

**Comment by KoalaBear84** [comment]
I cannot reproduce it. Tried with Greenshot, Snipping Tool and Windows + SHIFT + S

Tested with FireFox 59 and FireFox 60

Can you reproduce it?

**Comment by SmartManoj** [comment]
After updating , It is solved
