### ISSUE TITLE
Pause for 5 minutes

### ISSUE THREAD

**Issue by SmartManoj** [ffMathy/Shapeshifter#469]
In some cases we have to disable Shapeshifter ,so it is like to have an option like pause for 5 minutes

**Comment by ffMathy** [comment]
Who is "we"? And why do you need to disable Shapeshifter? Because of bugs?

**Comment by SmartManoj** [comment]
We -> The Users.Yes,Because of bugs like while in RDP session,MS Excel ...

**Comment by ffMathy** [comment]
I would rather just fix the issues then, which we will at some point. Are you a developer, and are you able to help perhaps?

I may consider a disable option in the future, but for now I would rather fix the most common errors.

**Comment by SmartManoj** [comment]
I am a Python developer :-)

**Comment by ffMathy** [comment]
Ah damn :+1:

Time to learn C#!

**Comment by SmartManoj** [comment]
> 
> 
> We -> The Users.Yes,Because of bugs like while in RDP session,MS Excel (copying data not worked in previous versions)...
> Because during those times if one close SS due to bugs,then he may able to forget to restart SS.

If even restarted later , the history will be lost
