### ISSUE TITLE
Unable to access https://shapeshifter.app

### ISSUE THREAD

**Issue by thejoshtaylor** [ffMathy/Shapeshifter#471]
**Describe the bug**
[https://ffmathy.github.io/Shapeshifter/](https://ffmathy.github.io/Shapeshifter/) redirects traffic to [https://shapeshifter.app/](https://shapeshifter.app/) which doesn't have a valid certificate name and won't allow traffic through. 

**To Reproduce**
1. Navigate to [https://ffmathy.github.io/Shapeshifter/](https://ffmathy.github.io/Shapeshifter/) or [https://shapeshifter.app/](https://shapeshifter.app/)
2. See error

**Expected behavior**
I was expecting to see a web page.

**Screenshots**
![image](https://user-images.githubusercontent.com/38962862/40074085-8bbc94fe-582d-11e8-87c1-cb34e5d80b32.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 66.0.3359.139

**Additional context**
I have tried this multiple times yesterday and today (2018May15) to no avail.

**Comment by ffMathy** [comment]
Thanks for your report! We are aware of this and are fixing it as we speak. Keep track of #455 to see more!
