### ISSUE TITLE
Tray icon

### ISSUE THREAD

**Issue by szepeviktor** [ffMathy/Shapeshifter#48]
If we have options (like using Ctrl+V only - no up&down -  to operate) they could go to a tray icon.

**Comment by ffMathy** [comment]
I will bump this up to version 6.1.0, since it is quite important for other features to be there as well.

**Comment by szepeviktor** [comment]
Could you add an option for *one-handers*? I mean using CTRL+V to cycle through clipboard items.

**Comment by ffMathy** [comment]
Aaaah, a *setting* for one-handers is a good idea. Can you post it in the other issue that I closed? Then I will re-open it.
