### ISSUE TITLE
Ctrl+Shift+V

### ISSUE THREAD

**Issue by monkeydg** [ffMathy/Shapeshifter#5]
A lot of apps use this key combination to paste as plain text - I know I use it quite a lot. As it stands, Shapeshifter works with about a 20% success rate when trying it, and only with the most recently copied file.So far, it's been my only gripe with your program. If you fix that, you'll be my new best friend :)

**Comment by KoalaBear84** [comment]
Hmm. I also experienced this. I think it is not working because you need to fully press and release the V, but still holding the CTRL + SHIFT.

1. Press CTRL + SHIFT
2. Press V
3. Release V
4. Release CTRL + SHIFT

Maybe Windows also works if the three were all pressed and also release CTRL or SHIFT before releasing the V.

**Comment by ffMathy** [comment]
Thanks for your awesome contributions to describing this issue! Shapeshifter development will continue soon. I'll get back to this issue as it is addressed.

**Comment by monkeydg** [comment]
Awesome! I love the dev/community communication here.

**Comment by ffMathy** [comment]
Me too!

Remember that for every $1 we get in donations, we spend that on focusing more on Shapeshifter. We've been working on it for almost 5 years, and all that for free (in our spare time).

We want to make Shapeshifter 5 the best release available. If people start donating just a tiny bit, it'll get more attention from us.

**Comment by monkeydg** [comment]
I'll definitely look into donating! Thanks for the responses.

**Comment by ffMathy** [comment]
This will be fixed soon.

**Comment by ffMathy** [comment]
I am now working on this. Expect it to be fixed in a day or two.

**Comment by monkeydg** [comment]
Awesome news!

**Comment by ffMathy** [comment]
This has now been resolved!

**Comment by monkeydg** [comment]
I'm beyond impressed. Well done.

**Comment by ffMathy** [comment]
Thank you. I am impressed of your feedback as well. Keep it up - as the creator of the program, I don't always see all bugs, even though they may seem obvious. Feedback like this helps me do my work.
