### ISSUE TITLE
Can't copy image file

### ISSUE THREAD

**Issue by dixours** [ffMathy/Shapeshifter#50]
Hi !

With last release (shapeshifter-v6.0.0.1512) I can't copy an image file (entire image, not only image name as text) using Ctrl-C/Ctrl-V (but "right-clic" then "Paste" works)

Have a nice day !

**Comment by ffMathy** [comment]
So, an image file (as in kitten.jpg), but not an image region (as in selecting a region of an image in Paint and copying it)? There is a difference between the two.

**Comment by dixours** [comment]
I have an image file "Kitten.jpg" in my desktop and I would like to make a copy in the document folder.
Ctrl-C then Ctrl-V doesn't work when Shapeshifter is running (but right-clic then "Paste" command works.

It seems ShapeShifter 6.0.0.1512 works only with text.
I don't get this bug with ShapeShifter 5.0.0.107

**Comment by KoalaBear84** [comment]
See attached pull request to fix the issue.

**Comment by KoalaBear84** [comment]
Possible duplicate #25

**Comment by KoalaBear84** [comment]
Probably fixed with PR #52

**Comment by ffMathy** [comment]
#52 has been merged. Thanks @KoalaBear84! And @dixours, let me know if the issue persists with the latest version.

**Comment by dixours** [comment]
It works very well !! Thank you so much !!
