### ISSUE TITLE
Have a way to exit Shapeshifter

### ISSUE THREAD

**Issue by dixours** [ffMathy/Shapeshifter#51]
Hi !

With last release (shapeshifter-v6.0.0.1512) I can't shutdown Shapeshifter. I use Task Manager to kill the app... is there an other way ?

Thank you !

**Comment by ffMathy** [comment]
Shapeshifter 6 is still an alpha release meaning that it is not done yet.

We need to work on a way of exiting the application. Thanks for creating this issue.

**Comment by dixours** [comment]
Thank you ! 
This is a wonderful work, wish you the best !

**Comment by ffMathy** [comment]
Let's leave the issue open. Then you can also keep track of when it is done! :+1:

**Comment by ffMathy** [comment]
Do you often close Shapeshifter? If yes, why? Maybe we could instead solve your problems you are having. Also, would you prefer a tray icon for shutting down Shapeshifter, or a different approach?

**Comment by dixours** [comment]
I never close Shapeshifter 5.0.0.107 'cause it works very well (just the notification at every boot, about translation, very boring).
I have to close ShapeShifter 6.0.0.1512 because of the bug when I want to copy an image file ;-)

**Comment by ffMathy** [comment]
Fair enough.

The translation message will happen because your language has not been translated to yet. Unfortuantely, the translation service has been shut down. This will be resolved forever in Shapeshifter 6.

**Comment by ffMathy** [comment]
This is dependent on #48.
