### ISSUE TITLE
Can't fetch icon from UWP apps

### ISSUE THREAD

**Issue by ffMathy** [ffMathy/Shapeshifter#526]
Applications like Edge can't get their icons fetched.

See https://stackoverflow.com/questions/32001224/how-to-get-the-windows-store-app-icon-from-a-hwnd

**Comment by KoalaBear84** [comment]
We might try parameter value 2 for ICON_BIG, don't know if that will fix it, but it's worth a try.

**Comment by ffMathy** [comment]
Alright I got some of this working but I don't have time until next Tuesday to continue. I pushed my changes so far to develop, although it doesn't compile. Feel free to take over in the meanwhile if you want to give it a shot. You can look at where the compile failures are and that question on StackOverflow.

**Comment by ffMathy** [comment]
Fixed.
