### ISSUE TITLE
Exit without paste

### ISSUE THREAD

**Issue by zsbodnar** [ffMathy/Shapeshifter#55]
If I don't want to paste any items while I'm holding Ctrl+V, I have to press the Esc which is uncomfortable. Since only the Up/Down can be used to cycle through the items a Left arrow is at a better position.

**Comment by ffMathy** [comment]
That is a brilliant idea! I will include it in the next release.

**Comment by ffMathy** [comment]
This has now been resolved. You can also press "right" two times to exit.
