### ISSUE TITLE
Double paste

### ISSUE THREAD

**Issue by szepeviktor** [ffMathy/Shapeshifter#559]
v6.2018.530.2822 pastes twice when the UI is opened.
Quick pastes (within 300 ms) do it once.
Please advise.

**Comment by szepeviktor** [comment]
after some testing it freeze

```
2018-05-31 10:17:34.562 [#8296] [Shapeshifter.WindowsDesktop.Controls.Window.MainWindow] [INF]
Hiding user interface.

2018-05-31 10:17:34.562 [#8296] [Shapeshifter.WindowsDesktop.Mediators.PasteCombinationDurationMediator] [INF]
Firing AfterPasteCombinationReleased event.

2018-05-31 10:17:34.562 [#8296] [Shapeshifter.WindowsDesktop.Services.Clipboard.ClipboardInjectionService] [WRN]
Could not empty clipboard.

2018-05-31 10:17:34.562 [#8296] [] [VRB]
Reporting the log entry "Could not empty clipboard.".
```

**Comment by KoalaBear84** [comment]
Possibly #359 is related, not sure, need the logs to see.

**Comment by KoalaBear84** [comment]
Hmm, then it could be related to #559

**Comment by szepeviktor** [comment]
There is an AHK program on my PC I wrote.
It also hooks the keyboard but not Ctrl+V

**Comment by ffMathy** [comment]
Thank you for this report. I can't reproduce it. Even when showing the UI, it never double pastes anymore. @KoalaBear84 do you see it?

**Comment by ffMathy** [comment]
Thank you for this report. I can't reproduce it. Even when showing the UI, it never double pastes anymore. @KoalaBear84 do you see it?

**Comment by KoalaBear84** [comment]
Haven't tried it. I should also use Shapeshifter.. 😇

**Comment by ffMathy** [comment]
The latest prerelease is really good actually in terms of performance, but bug fixes are still not there yet.

Which is the most important issue for you to solve for it to be usable for you?

**Comment by szepeviktor** [comment]
Indeed Shapeshifter is a much better software than a month ago.

**Comment by ffMathy** [comment]
I fixed the one where it froze now.

**Comment by ffMathy** [comment]
I can replicate the issue now! Hang tight.

**Comment by ffMathy** [comment]
This is now completely fixed, and I doubt it will ever turn up again - I made the code around it a lot more robust. Thanks!
