### ISSUE TITLE
Paste as file 

### ISSUE THREAD

**Issue by Pandahisham** [ffMathy/Shapeshifter#57]
Often times i need to split codebases or lenghty documentations , paste as file would allow to cut part of doc open explorer/desktop ctrl v  + s (for save as) , type in the name and extension (may be autocomplete extension ?)

ux after thoughts , when splicing lengthy research docs , i frequently cut parts into separate files , so remembering the last extension would be nice , but also autocomplete suggestion (like typeahead.js) would appear as i type p(hp) TAB , j(s)TAB , c(offee) TAB , multiple suggestion can appear in a drop down sorted by frequency naviagble by both arrows and 1,2,3... hotkeys maybe.

PS: i wish node.js could do this type of stuff and i could contribute easily .... maybe i learn C# and start hacking

**Comment by ffMathy** [comment]
That sounds nice. Do you mean being able to save text as a file, or?

We could even try to infer the type of programming language you copied and then from that automatically detect the file extension needed.

**Comment by Pandahisham** [comment]
yap save text as file , and paste and rename in single go for any file in general , like photo1.jpeg pasted as nice.jpeg

**Comment by ffMathy** [comment]
This has been bumped to a later release, since we need to get a stable version out of Shapeshifter first I think.

**Comment by ffMathy** [comment]
This has now been fixed. Is the given functionality like you desired it or does it still need to be different? I added a new action to copy text as a file.

**Comment by Pandahisham** [comment]
Is there a change log somewhere ?
