### ISSUE TITLE
Your websites certificate is invalid

### ISSUE THREAD

**Issue by Xyolyp** [ffMathy/Shapeshifter#575]
**Describe the bug**
When I open the link to your website (https://shapeshifter.app/) I only see a certificate error.

![grafik](https://user-images.githubusercontent.com/13995942/43458093-386a66d6-94c9-11e8-97f9-7bd81e16cd71.png)
The text translates to "The connection is using a certificate that is not signed for this domain. Because HSTS is enabled firefox can't create an exception for the security rule. The certificate is valid for the domains: *.azurewebsites.net, *.scm.azurewebsites.net, *.azure-mobile.net, *.scm.azure-mobile.net, *.sso.azurewebsites.net"

**Comment by sumnone** [comment]
If you bypass the error and go to the site anyway, it's gone. 404 Web Site not found...

**Comment by FreshhhHub** [comment]
confirmed
can't find official d/l link for Windows x64 portable or exe setup

**Comment by itniels** [comment]
Hi @Xyolyp :)
Thanks for reporting.

There is an issue for migrating the site and getting it back up and running :)
So i will close this.
https://github.com/ffMathy/Shapeshifter/issues/580
