### ISSUE TITLE
Have description of actions be dynamically generated

### ISSUE THREAD

**Issue by ffMathy** [ffMathy/Shapeshifter#62]
Right now, the description of actions is static. If we make it dynamically generated, it will allow the `CopyLinkAction` to (for instance) produce helpful descriptions that are part of its data.

So instead of "Open the link that is present in the clipboard", we show "Opens http://google.com" if that link is copied.

**Comment by KoalaBear84** [comment]
It would be a good nice to have indeed.

**Comment by ffMathy** [comment]
Done.
